### ISSUE TITLE
New version 0.13.0 crashes during mixin stage.

### ISSUE THREAD

**Issue by ewe2** [jellysquid3/Lithium#550] opened 2024-08-14 06:21 UTC
### Version Information

lithium-fabric-mc1.21.1-0.13.0

### Expected Behavior

The mod should load without error.

### Actual Behavior

The mod caused a crash during the mixin stage, see crash report. 

### Reproduction Steps

[crash-2024-08-14_16.08.50-client.txt](https://github.com/user-attachments/files/16608321/crash-2024-08-14_16.08.50-client.txt)

### Other Information

Minecraft loads normally when mod is disabled, so it is reasonably certain to be the sole cause of issues.

**Comment by Lolothepro** [comment] 2024-08-14 06:42
Duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/521

**Closed as not planned** 2024-08-15 01:01 UTC
Labels: E-duplicate
