### ISSUE TITLE
stacked tnt explode at the wrong height

### ISSUE THREAD

**Issue by pwouik** [jellysquid3/Lithium#66] opened 2020-06-30 20:24 UTC
### Expected Behavior
tnts at the exact same position explode at the same position

### Actual Behavior
stacked tnt can explode a bit higher,somtime more than 1 block, outside water
### Reproduction Steps

1.summon a bunch of tnt at one spot in a 1 high water pool
execute as @e[type=minecraft:minecart] run summon tnt ~ ~2 ~-3 {Fuse:20}
2.it blow up blocks on top

### Attachments
![2020-06-30_21 08 56](https://user-images.githubusercontent.com/62726872/86173298-0fffee80-bb20-11ea-98a2-fdaa11beaebd.png)
![2020-06-30_21 09 07](https://user-images.githubusercontent.com/62726872/86173096-bb5c7380-bb1f-11ea-8c4f-7c3a668e0d48.png)

**Comment by Ueaj-Kerman** [comment] 2020-07-02 17:02
isn't this a vanilla bug?

**Comment by pwouik** [comment] 2020-07-02 17:07
No,I tested in vanilla,it didn't happened and then I removed mods to test and it was lithium because it work well without

**Comment by 2No2Name** [comment] 2020-07-03 15:17
Which Minecraft version and which mod version did you use? The tnt behavior regarding that was changed times in the last few months in vanilla as well.

**Comment by 2No2Name** [comment] 2020-07-03 15:29
I was able to reproduce this in 1.16.1.

[lithium #66.zip](https://github.com/jellysquid3/lithium-fabric/files/4870415/lithium.66.zip)

**Comment by 2No2Name** [comment] 2020-07-03 15:34
Okay I fixed the bug, thank you for the report. It was caused by mojang's special case fix for tnt eye height not being added to the optimized implementation in lithium. Pullrequest will be opened soon.

**Comment by jellysquid3** [comment] 2020-07-04 06:50
Fixed with `mc1.16.1-0.5.0`.

**Closed as completed by jellysquid3** 2020-07-04 06:50 UTC
Labels: T-bug
