### ISSUE TITLE
Lithium crashes on startup for Fabric 1.21 and 1.21.1

### ISSUE THREAD

**Issue by JustPixeled** [jellysquid3/Lithium#549] opened 2024-08-13 15:48 UTC
Description:
Latest Lithium releases for 1.21 and 1.21.1 crashes my 1.21 and 1.21.1 Prism Launcher instances on start up.

------------------------
Mod version: lithium-fabric-mc1.21-0.13.0 (for 1.21) and lithium-fabric-mc1.21.1-0.13.0 (for 1.21.1)

Reproduction Steps:
(I'll be going through the steps for 1.21, but it's pretty much the same for 1.21.1)
1. Create or use an existing 1.21 Fabric 0.16.0 MultiMC/Prism Launcher instance.
2. Download Lithium version lithium-fabric-mc1.21-0.13.0
3. Launch the game
4. Watch as it crashes quite quickly.

------------------------
Crash Report File:
https://drive.google.com/file/d/1LZXl_rBriO6ueAHKqRjR0PbOXNdvAWGn/view?usp=sharing

------------------------
Prism Launcher instance:
https://drive.google.com/file/d/1Gu4O4lj-4QVP_5RzzKmVFEJEcBIk-jrT/view?usp=sharing

------------------------
Additional Information:
When Lithium is not installed the game runs as usual.

**Comment by Lolothepro** [comment] 2024-08-13 15:54
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onExplosion(Lnet/minecraft/class_243;Lnet/minecraft/class_1297;)F in carpet.mixins.json:Explosion_scarpetEventMixin from mod carpet failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap fabric-carpet-refmap.json`

**Comment by pajicadvance** [comment] 2024-08-13 15:54
Duplicate of #521

**Closed as not planned by pajicadvance** 2024-08-13 15:54 UTC
Labels: E-duplicate
