### ISSUE TITLE
Game crashes when launching

### ISSUE THREAD

**Issue by aubeywan** [jellysquid3/Lithium#552] opened 2024-08-15 17:33 UTC
### Version

> lithium-fabric-mc1.21-0.13.0

### Reproduction Steps

> I updated from Lithium mc1.21-0.12.7, but when I launch Minecraft 1.21 it crashes.
>

### Crash Report File

> 
[crash-2024-08-15_13.20.44-client.txt](https://github.com/user-attachments/files/16628032/crash-2024-08-15_13.20.44-client.txt)

### Additional Information

> The crash does not happen with Lithium mc1.21-0.12.7 or with Lithium not installed.

**Comment by Lolothepro** [comment] 2024-08-15 17:38
duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/521

**Closed as completed** 2024-08-15 17:55 UTC
