### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Haocen2004** [jellysquid3/Lithium#119] opened 2020-08-29 06:37 UTC
### Reproduction Steps
I was afk then the server crash

### Crash Report File
[File](https://gist.github.com/Haocen2004/d1d4d3e84ae48c080d985f5514778c6f)

**Comment by 2No2Name** [comment] 2020-08-29 15:05
You can put `ai.nearby_entity_tracking=false` into your Lithium Config file to work around this issue until it is fixed

**Comment by 2No2Name** [comment] 2020-08-30 16:16
Does the problem also occur when you are not using carpet and carpet extra?
(so far all users who experienced this problem were using those mods)

**Comment by Haocen2004** [comment] 2020-08-30 16:22
I'll try  it , but so far the server hasn't crashed again ( I haven't changed the config or remove any mods)

**Comment by 2No2Name** [comment] 2020-08-30 16:27
Do you have carpet's unloadedEntityFix enabled during the crash?

**Comment by Haocen2004** [comment] 2020-08-30 16:28
yes

**Comment by 2No2Name** [comment] 2020-08-30 16:41
carpet's unloadedEntityFix is probably redundant and now messes up the chunk entity lists. Comments at https://bugs.mojang.com/browse/MC-108469 say the bug is no longer reproducible in 1.16, so the "fix" now probably causes a problem.

**Comment by Haocen2004** [comment] 2020-08-30 16:56
Thanks for your help. If the server does not crash within a week, I will close this issue

**Comment by jellysquid3** [comment] 2020-08-31 06:17
We're going to go ahead and close this issue as it looks like we're dealing with a problem in Carpet (see https://github.com/gnembon/fabric-carpet/issues/443). The author has since pushed a commit to their own mod which removes the now irrelevant patch, so we think this problem should be solved.

If you experience this crash again, please leave a comment asking for the issue to be re-opened. Thanks!

**Closed as completed by jellysquid3** 2020-08-31 06:17 UTC
Labels: T-bug, E-external, S-confirmed
