### ISSUE TITLE
Hopper interact with containers worngly.

### ISSUE THREAD

**Issue by Youmiel** [jellysquid3/Lithium#248] opened 2021-06-21 11:04 UTC
### Version Information

lithium-fabric-mc1.17-0.7.1

### Expected Behavior

> Hoppers should take items from the container above it, and stop taking items if the container is removed/disconnected.

### Actual Behavior

> The behavior is not expected.

### Reproduction Steps

> Place a large chest above hopper, fill it with items
> Destory the half above the hopper
> **Hopper takes items from another half, which is not connected to the hopper** 
> Replace the chests, hopper stops taking items.
> More details see video.

### Other Information

Game version: Minecraft 1.17
Fabric version: fabric-loader-0.11.3
Mod list:
* lithium-fabric-mc1.17-0.7.1

This issue might be related to CaffeineMC/lithium-fabric#247

https://user-images.githubusercontent.com/70473080/122752271-4f8c9100-d2c3-11eb-836d-b6dd0d405950.mp4

**Comment by 2No2Name** [comment] 2021-06-21 12:52
Thanks for the detailed bug report. The cause was a mistake in the inventory caching code which affected double inventories above hoppers. It is fixed in https://github.com/CaffeineMC/lithium-fabric/commit/1736fa488be5a12672fca1aab0069ae9b5361c25 and will be in the next release

**Closed as completed** 2021-06-21 15:59 UTC
Labels: T-bug, P-high, A-vanilla-parity, S-confirmed, R-pending-release, F-good-issue
