### ISSUE TITLE
Lithium broke save.

### ISSUE THREAD

**Issue by K0-RR** [jellysquid3/Lithium#173] opened 2020-12-14 10:45 UTC
After this crash everytime when I try to load the world it freezes (I can't even move camera) after loading.
Crash report - https://hatebin.com/fnnwhwzfft

**Comment by 2No2Name** [comment] 2020-12-14 13:13
Please provide the list of mods you have installed and check whether the crash stops occuring when you uninstall lithium.

**Comment by K0-RR** [comment] 2020-12-14 13:26
Disabling (MultiMC) Lithium "fixes" world, reenabling Lithium still causes freeze.
Mod list:
               accurateblockplacement: Accurate Block Placement 1.0.8
               adorn: Adorn 1.12.2+1.16.4
               advdebug: Advancements Debug 2.2.0
               allstackable: All Stackable 1.2.7
               allure: Allure 1.2.8
               angerable-patch: Angerable Patch 1.1.0-1.16.4
               appleskin: AppleSkin 1.0.11
               astromine: Astromine 1.12.0+fabric-1.16.4
               astromine-core: Astromine: Core 1.12.0+fabric-1.16.4
               astromine-discoveries: Astromine: Discoveries 1.12.0+fabric-1.16.4
               astromine-foundations: Astromine: Foundations 1.12.0+fabric-1.16.4
               astromine-technologies: Astromine: Technologies 1.12.0+fabric-1.16.4
               astromine-transportations: Astromine: Transportations 1.12.0+fabric-1.16.4
               atmosfera: Atmosfera 1.3.5
               autoconfig1u: Auto Config v1 Updated 3.3.1
               autoswap: Autoswap 1.16.2-fabric0.17.2-1.0.1
               battletowers: Battle Towers 3.3.1-beta-1.16.4
               bedrockify: BedrockIfy 0.2.0
               beebetter: Bee Better 1.8.0-1.16.4
               bendy-lib: Bendy api 0.2.3
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
               betternether: Better Nether 5.0.4
               betterstones: Better Stones 0.0.4
               biomemakeover: Biome Makeover 1.16.4-1.1.5
               blade: Blade 2.0.0
               blame: Blame 2.2.4
               blockus: Blockus 1.6.8+1.16.4
               blue_endless_jankson: jankson 1.2.0
               byg: BYG 1.1.3
               campanion: Campanion 1.3.0+build.49
               cardinal-components-base: Cardinal Components API (base) 2.7.9
               cardinal-components-block: Cardinal Components API (blocks) 2.7.8
               cardinal-components-chunk: Cardinal Components API (chunks) 2.7.8
               cardinal-components-entity: Cardinal Components API (entities) 2.7.9
               cardinal-components-item: Cardinal Components API (items) 2.7.9
               cardinal-components-level: Cardinal Components API (world saves) 2.7.8
               cardinal-components-util: Cardinal Components API (utilities) 2.7.8
               cardinal-components-world: Cardinal Components API (worlds) 2.7.8
               carpet: Carpet Mod in Fabric 1.4.12
               cavebiomes: Cave Biomes 0.5.1
               charm: Charm 2.1.4
               charmonium: Charmonium 2.1.4
               chat_heads: Chat Heads 0.2.1+1.16.2
               chesttracker: Chest Tracker 0.7.9
               chunkpregen: Fabric Chunk Pregenerator 0.3.3
               cinderscapes: Cinderscapes 1.3.0+build.51
               clear-skies: Clear Skies 1.5.53
               climbable: Climbable 0.2.0
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.8
               cloth-common-events-v1: Cloth Common Events v1 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
               cloth-utils-v1: Cloth Utils v1 1.4.5
               com_electronwill_night-config_core: core 3.6.2
               com_electronwill_night-config_toml: toml 3.6.2
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               com_typesafe_config: config 1.4.0
               commandaliases: Command Aliases 0.3.0
               computercraft: CC:T for Fabric 1.91.2
               crimsonmoon: Crimson Moon 1.2.3-1.16.2
               croptopia: Croptopia 1.0.5-1.16.3-FABRIC
               crowdin-translate: CrowdinTranslate 1.2
               crumbs: Crumbs 1.0.2+1.16.4-fabric
               cullleaves: Cull Leaves 1.0.0
               curios: Curios API 0.0.10-1.16.3
               custom_hud: CustomHud 1.0.0
               customportals: Custom Portals 1.3.0
               darkness: True Darkness 1.6.50
               dawn: Dawn API 1.6
               dehydration: Dehydration 1.0.8
               dishes: Delicious Dishes 2.0.0
               dungeons_of_exile: Dungeons of Exile 1.1.1
               durabilityviewer: Giselbaers Durability Viewer 1.16.4-fabric0.25.1-1.9
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               elytra-recipe: Elytra Recipe 1.0.1
               emotecraft: Emotecraft 1.2.3
               environmentz: EnvironmentZ 1.0.7
               expandedconcrete: Expanded Concrete 0.0.2
               fabriblocks: FabriBlocks 1.2.1
               fabric: Fabric API 0.28.1+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
               fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
               fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabrication: Fabrication 1.2.3_02
               fabricloader: Fabric Loader 0.10.8
               fairenchanting: FairEnchanting 1.2.0
               fallflyinglib: FallFlyingLib 1.1.0
               fallingleaves: Falling Leaves 1.2
               fermion: Fermion 2.8.215
               fermion-gui: Fermion GUI 2.5.215
               fermion-modkeys: Fermion Modifier Keys 1.9.206
               fermion-orientation: Fermion Orientation 1.1.205
               fermion-simulator: Fermion Simulator 1.8.215
               fermion-varia: Fermion Varia 2.6.215
               fiber: fiber 0.23.0-2
               flight_rings: Flight Rings 1.4.2
               flyring: Ring of Flight 0.1.0+1.16.4
               gbfabrictools: GBfabrictools 1.3.2+1.16.4
               grass_pass: Grass Bypass 1.0.0
               grindenchantments: Grind Enchantments 1.1.3+1.16.3
               headsdowndisplay: Heads down display 0.0.0
               images: Images 0.4.0+1.16.4
               immersive-cursedness: Immersive Cursedness 1.2.1
               inventory_control_tweaks: Inventory Control Tweaks 1.1+MC1.16.2-1.16.4
               inventoryhud: Inventory HUD + 3.1.3
               inventorytabs: Inventory Tabs 0.2.3-1.16.4
               invview: InvView 1.2.0-1.16.2+
               itemscroller: Item Scroller 0.15.0-dev.20201103.183933
               jankson: Jankson 3.0.1+j1.2.0
               javax_vecmath_vecmath: vecmath 1.5.2
               jumplessstep: Jumpless Step 0.1.0+1.16.1
               lakeside: Lakeside 1.0.3+1.16.4
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               lapisreserve: Lapis Reserve 1.0.6
               libblockattributes_core: LibBlockAttributes (Core) 0.8.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
               libblockattributes_items: LibBlockAttributes (Items) 0.8.4
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.2.1+1.16.3
               library_of_exile: Library of Exile 1.0.6
               libstructure: LibStructure 1.5
               lightstones: Lightstones 1.2
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               maelstrom_library: Maelstrom Library 0.4.1
               magna: Magna 1.4.3-1.16.2
               makkit: Makkit 1.1.0
               malilib: MaLiLib 0.10.0-dev.21+arne.2
               mambience: MAmbience 2.1.0+1.16.2
               microdurability: microDurability 0.3.0+1.16.3
               midnight-hats: Midnight Hats 2.0.1
               minecraft: Minecraft 1.16.4
               minegate-moreblocks: MineGate - MoreBlocks 1.0.1
               minimaltweaks: Minimal Tweaks 1.0.3
               mixedslab: Mixed Slab 1.16.3-1.2
               mobs_attempt_parkour: Mobs Attempt Parkour 0.2.1-1.16.3
               modmenu: Mod Menu 1.14.13+build.19
               modupdater: ModUpdater 1.1.11+1.16.2-rc2
               more_gems: More Gems 1.1.12
               moreblocksmod: More Blocks Mod 1.0.0
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
               mostructures: Mo' Structures 1.0.1+mc.1.16.4
               mythicmetals: Mythic Metals 0.9.7
               namepain: Name Pain 1.3.1
               nbtcrafting: NBT Crafting 2.0.1+mc1.16.4
               nookbuild: NookBuild 1.2.1
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               nourish: Nourish 1.1.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
               org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
               org_joml_joml: joml 1.9.25
               origins: Origins 0.4.5
               patchouli: Patchouli 1.16.4-48-FABRIC
               phosphor: Phosphor 0.6.0+build.7
               photoallergiccreepers: Photoallergic Creepers 0.2.0+1.16.1
               piglib: Piglib 1.0.1
               playerabilitylib: Pal 1.2.1
               polymorph: Polymorph 0.0.5-1.16.3
               rare-ice: Rare Ice 0.2.2
               reach-entity-attributes: Reach Entity Attribute 1.0.2
               repurposed_structures: Repurposed Structures 1.16.4-1.7.3
               reroll: Reroll 1.0.2-1.16.2
               ringsofascension: Rings of Ascension 1.1.1
               rocks: This Rocks! 1.2.2
               roughlyenoughitems: Roughly Enough Items 5.8.8
               roughlyenoughitems-api: REI (API) 5.8.8
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.8
               roughlyenoughitems-runtime: REI (Runtime) 5.8.8
               rpgstats: RPGStats 2.3.2+1.16.3
               satin: Satin 1.4.1
               seasons: Fabric Seasons 1.0.3-BETA
               shapes: Shapes 2.0.0+build.10
               simpleteleporters: Simple Teleporters 2.2.1
               simplexterrain: Simplex Terrain 0.7.2
               slyde: Slyde 1.1
               snowdrift: Snowdrift ${version}
               snowy_leaves: Snowy Leaves 1.16.1-1.3.1
               sodium: Sodium 0.1.0
               special-circumstances: Special Circumstances 1.8.215
               spiceoffabric: Spice of Fabric 1.2.6+1.16.3
               splash: Splash 1.2.0
               spruceui: SpruceUI 1.6.4
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               structure-helpers: Structure Helpers 3.0.0
               tagboard: Tagboard 1.0.1+1.16.4
               team_reborn_energy: Energy 0.1.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.3
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.3
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               texp: Terran Expansion 1.1.1
               tiered: Tiered 1.2.0-beta-1.16.4
               tinytweaks: TinyTweaks 1.1.2
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               torohealth: ToroHealth Damage Indicators 1.16.4-fabric-3
               trinkets: Trinkets 2.6.7
               tweed: Tweed API 3.0.0-beta.15
               unearthed: Unearthed 1.0.5
               vanilla-toolsets: Vanilla Toolsets 1.3.0
               vanillaenhanced: VanillaEnhanced 1.3.1
               visp: Visp 0.0.3
               voyager: Voyager 1.0.0
               water-erosion: Water Erosion 1.1.1
               waystones: Waystones 1.0.10
               wild_explorer: Wild Explorer 1.3
               wildworld: Wild World 1.3.0+1.16.2
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               woods_and_mires: Woods and Mires 1.0.4+1.16.3
               woodsplus: Woods Plus 0.0.2
               worldtime: WorldTime 1.16.4-fabric0.25.1-1.2.4
               wrenchable: Wrenchable 1.0.0+1.16.1
               xaerobetterpvp: Better PVP Mod 20.29.0
               xpstorage: XP Storage 1.2+1.16.4
               yungsapi: YUNG's API 1.16.4-Fabric-1

**Comment by 2No2Name** [comment] 2020-12-14 15:01
One of your mods is modifying the cactus block. Do you have any idea which one that is?

**Comment by K0-RR** [comment] 2020-12-15 15:10
Mods I use that add cactuses: terrestria; biome makeover; byg.

**Comment by K0-RR** [comment] 2020-12-15 15:14
And more important - I use these mods for a while now and Lithium was working fine but recently I added Simplex world generator mod. The world on which the crash occured was generated by Simplex.

**Comment by 2No2Name** [comment] 2020-12-20 18:22
I have no idea what is causing this bug. If you have the time for it you could try removing half of the mods at a time (keep lithium) to search which other mod is crashing together with lithium.

**Comment by jellysquid3** [comment] 2021-01-25 06:55
I'm closing this as an external issue because it's not clear to me how Lithium is causing this and the error trace seems to more likely point to another mod as fault. If you are able to reduce this to a minimally reproducible example (i.e. the specific mods that cause this crash) and can demonstrate adding Lithium is what breaks it, please update this issue.

**Closed as completed by jellysquid3** 2021-01-25 06:55 UTC
Labels: T-bug, E-external
