### ISSUE TITLE
Compatibility issue with EvilCraft

### ISSUE THREAD

**Issue by uhloin** [jellysquid3/Lithium#578] opened 2024-11-05 15:05 UTC
### Version Information

Minecraft 1.21.1
NeoForge: neoforge-21.1.68-installer.jar 
Lithium: lithium-neoforge-0.14.0-snapshot+mc1.21.1-build.88.jar

### Expected Behavior

In the EvilCraft after kill mob under some conditions spawned a new "ghost" mob that is invisible and untouchable until get some magic ring.

### Actual Behavior

"ghost" mob blocks movement of player

### Reproduction Steps

1. Install Evilcraft + Cyclops core
2. In creative mode make long narrow horizontal corridor
3. Get zombie spawn egg, Vengeance pickaxe, some sword
4. Switch to survive mode
5. Break some stone with Vengeance pickaxe (1 stone block is enough)
6. Spawn a zombie
7. Kill zombie
8. Try move along the corridor - invisible spirit of zombie will block movement

### Other Information

cyclopscore-1.21.1-neoforge-1.25.2-634.jar 
EvilCraft-1.21.1-neoforge-1.2.59.jar 

Related bug in EvilCraft:
https://github.com/CyclopsMC/EvilCraft/issues/1070

**Comment by 2No2Name** [comment] 2024-11-11 20:21
I think I found the reason for this issue. The code looks like lithium also allows all mobs to collide with dead shulkers incorrectly in some conditions. Confirmed it with the auto-jump functionality, which causes the player to jump onto dead shulkers with the latest lithium release

**Comment by 2No2Name** [comment] 2024-11-11 21:06
Please test the following workaround and report back:
Add `mixin.entity.collisions.intersection=false` to the lithium properties file in the config folder and restart the game.

**Comment by hallister** [comment] 2024-11-12 17:56
Confirmed that property fixes the issue. Ghost entities are still there but no longer cause collisions.

**Comment by uhloin** [comment] 2024-11-12 17:58
Yes, no more collisions

**Comment by 2No2Name** [comment] 2024-11-12 20:53
Thanks, the fix will be included in the next release

**Closed as completed** 2024-11-17 20:52 UTC
Labels: T-bug, A-mods, R-pending-release, F-good-issue, F-has-workaround
