### ISSUE TITLE
Command block executing carpet mod command `script run game_tick()` crashes game if Lithium is installed

### ISSUE THREAD

**Issue by James103** [jellysquid3/Lithium#239] opened 2021-06-08 20:11 UTC
### Version

Minecraft Version: 1.17
```
Mods:
  [✔️] fabric-carpet-1.17-1.4.40+v210608
  [✔️] lithium-fabric-mc1.17-0.7.0
```

### Reproduction Steps

1. Create a new Minecraft 1.17 instance and install the above mods.
2. Also install OpenJDK 16 (OpenJ9) and let your Minecraft installation run off the Java 16 installation.
3. Create a new world with cheats enabled.
4. Run `/give @p minecraft:command_block{BlockEntityTag:{Command:"script run game_tick()",auto:1b}} 1`.
5. Place the resulting command block down.
6. Notice the chat output and the subsequent crash.

### Crash Report File

Crash report is at https://gist.github.com/James103/b813d632b05b0271c39c6c6010114548
Most recent Minecraft Log: [latest.log](https://github.com/CaffeineMC/lithium-fabric/files/6619320/latest.log)

### Additional Information

* Installing NotEnoughCrashes as well and reproducing suggests that the crash is caused by Lithium.
* If Lithium is not installed, following the above reproduction steps instead causes the command block in steps 5-6 to print "= **true** _(##ms)_" to chat and not crash nor output any exceptions.

**Comment by 2No2Name** [comment] 2021-06-08 20:14
Duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/175

**Closed as completed by 2No2Name** 2021-06-08 20:14 UTC
