### ISSUE TITLE
[1.21.1] Game does not recognize VPB Arms Dealer Workstation

### ISSUE THREAD

**Issue by thisavowed** [jellysquid3/Lithium#582] opened 2024-11-11 07:13 UTC
### Version Information
> lithium-neoforge-0.14.0-snapshot+mc1.21.1-build.88

### Expected Behavior
> Villager must become an Arms Dealer (Job) after recognizing the workstation.

### Actual Behavior
> Villager does not become an Arms Dealer.

### Reproduction Steps
(With Lithium in the mod folder)
1. Boxing in an area to make sure a villager does not attempt at other workstations.
2. Placing a Vic's Point Blank [Arms Dealer Workstation] inside the box.
3. Placing a jobless villager inside the box.

(Without Lithium, this produces the expected behavior no problem)

### Other Information
Vic's Point Blank: pointblank-neoforge-1.21-1.7.8

14 other mods, but only when Lithium was removed did I succeed with the expected outcome.

**Comment by 2No2Name** [comment] 2024-11-11 19:36
Investigation into the issue is not easily possible as the other mod is licensed as ARR and thus we cannot read their source.

**Comment by 2No2Name** [comment] 2024-11-11 19:45
Possible workaround:
Add `mixin.ai=false` to the lithium.properties file in the config folder.
If that fixes the issue, you can check the available sub-settings one by one (to avoid disabling such a large part of lithium's optimizations): https://github.com/CaffeineMC/lithium-fabric/blob/develop/lithium-neoforge-mixin-config.md

**Comment by 2No2Name** [comment] 2024-11-12 13:28
Closing this until information that is helpful with fixing the issue is provided

**Closed as completed** 2024-11-12 13:27 UTC
Labels: T-bug, F-help-wanted, A-mods, E-will-not-fix, F-good-issue

**Comment by 2No2Name** [comment] 2024-11-28 13:17
Probably fixed in the new release due to #594 being fixed
