### ISSUE TITLE
Wither is able to break unbreakable blocks.

### ISSUE THREAD

**Issue by MatthewClair** [jellysquid3/Lithium#19] opened 2020-03-07 06:57 UTC
Issue: Blocks that withers shouldn't be able to break are able to be broken.  Ex: Bedrock.

Expected: Withers shouldn't be able to break bedrock since they can't in vanilla.

Repro: Create a wither in the end under the bedrock portal platform.  The wither will be able to break the bedrock and end portal blocks inside.

**Comment by jellysquid3** [comment] 2020-03-07 07:11
I cannot reproduce this issue in the latest release of Lithium (0.4.4). Can you please verify that you are using the latest version, and if so, can you provide a client/server log file?

![2020-03-07_01 19 42](https://user-images.githubusercontent.com/1363084/76138988-1683cb00-6044-11ea-960b-80d348402567.png)

**Comment by samolego** [comment] 2020-03-07 07:25
Hi! I had the same problem after updating to 0.4.4 yesterday. I'm using the latest Fabric API as well.

EDIT: there don't seem to be any errors in server log file ...

**Comment by jellysquid3** [comment] 2020-03-07 07:33
I suspect the issue here could be that we are not properly initializing the "last visited" coordinate, so if the explosion starts at (0, 0), it will see only air blocks and cause weirdness like this. Given that the end portal is usually always created in chunk (0, 0), it seems the likely culprit.

**Comment by jellysquid3** [comment] 2020-03-07 07:43
It appears the coordinate initialization bug was in fact the cause of this issue, and has been resolved with https://github.com/jellysquid3/Lithium/commit/bde42c8ad0926f0e8b56efb4dd30fdc424dd2f97. 

I have published Lithium 0.4.5 on CurseForge (currently under review) with the aforementioned bug fix. Thank you for the report.

**Closed as completed by jellysquid3** 2020-03-07 07:43 UTC
Labels: T-bug, P-high

**Comment by samolego** [comment] 2020-03-07 08:07
Thank you for such a quick fix & response!
