### ISSUE TITLE
Hostile mobs run into lava to get to you

### ISSUE THREAD

**Issue by varencilator** [jellysquid3/Lithium#238] opened 2021-06-06 22:34 UTC
### Expected Behavior
Hostile mobs will stop when it recognizes there is lava between you and it.

### Actual Behavior
Hostile mobs ignore when there is lava in its path to its target and walk right into it to try to get to you.

### Reproduction Steps
Make any set up where there is one path between you and a hostile mob (like a zombie) and place lava either in the ground or over the ground.
Make sure you're in survival and see its behavior.

### Attachments
https://i.imgur.com/Pp2f9Sq.mp4

**Comment by 2No2Name** [comment] 2021-06-08 02:06
Which version of lithium and which other mods are installed on the server? I cannot reproduce this one the dev branch

**Comment by varencilator** [comment] 2021-06-08 21:18
This was on 0.6.4. I tried it with just fabric api and lithium and the problem still occurs. Going to see if 0.6.5 has this issue -edit: occurs in 0.6.5 as well.
imgur of the setup (just screenshots but I spawned them past the lava): https://imgur.com/a/LuHnaRt
Fabric api version 0.33.0
lithium 0.6.4 or 0.6.5

**Comment by 2No2Name** [comment] 2021-06-08 21:53
Did you place the lava after the monsters started attacking you?

**Comment by varencilator** [comment] 2021-06-09 02:09
Nope, I spawned them after the lava setup was already in place. Here's an actual vid: https://imgur.com/a/UGepATX 
Excuse the weird crop, didn't realize my obs display wasn't centered.
Also, tried taking out lithium and trying fabric api only and the problem doesn't occur

**Comment by 2No2Name** [comment] 2021-06-09 10:16
Can reproduce it now, put myself in a cave and they just walk into the lava

**Comment by 2No2Name** [comment] 2021-06-09 11:34
This should be fixed in https://github.com/CaffeineMC/lithium-fabric/actions/runs/921538847

**Comment by 2No2Name** [comment] 2021-06-09 17:02
Fixed in Lithium 0.6.6. Thanks for the good report and the extra explanatory screenshots

**Closed as completed by 2No2Name** 2021-06-09 17:02 UTC
Labels: T-bug, A-vanilla-parity, S-confirmed
