### ISSUE TITLE
Falling into one block deep water makes player take damage

### ISSUE THREAD

**Issue by Juru111** [jellysquid3/Lithium#142] opened 2020-09-22 17:02 UTC
### Expected Behavior
Falling into one block deep water neglate all fall damage.

### Actual Behavior
Falling into one block deep water makes player take damage - damage scales with height of fall.

### Reproduction Steps
1. Dig one block hole in flat area
2. Fill that hole with water
3. Make sure that player fall into that water
4. Player takes damage

###Tested on:
Minecraft fabric server with:
lithium-fabric-mc1.16.3-0.5.5

Minecraft fabric client (singleplayer) with:
fabric-api-0.21.0+build.407-1.16
lithium-fabric-mc1.16.3-0.5.5
modmenu-1.14.6+build.31
shulkerboxtooltip-2.3.1+1.16.3
Xaeros_Minimap_20.23.0_Fabric_1.16.3
XaerosWorldMap_1.11.0_Fabric_1.16.3

### Attachments
Clear save
[Fall into Water Lithum.zip](https://github.com/jellysquid3/lithium-fabric/files/5262921/Fall.into.Water.Lithum.zip)

**Comment by 2No2Name** [comment] 2020-09-22 17:04
Duplicate of https://github.com/jellysquid3/lithium-fabric/issues/141, which I accidently closed before the new release was out

**Comment by OrangeCatUnderscore** [comment] 2020-09-22 23:21
idk if this is helpful, but i did some testing, this does not affect clutch bucketing

**Comment by jellysquid3** [comment] 2020-09-23 15:01
Fixed in [Lithium 0.5.6](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.3-0.5.6).

**Closed as completed by jellysquid3** 2020-09-23 15:01 UTC
Labels: T-bug, S-confirmed
