### ISSUE TITLE
[Question] Furnaces stop working/reset smelting progress

### ISSUE THREAD

**Issue by storiofmylife** [jellysquid3/Lithium#379] opened 2022-07-25 16:13 UTC
I've no idea if this is even a Lithium issue, or if there's something inside Lithium that has an anti-lag feature to limit smelting. I can't replicate it efficiently, there's no error log anywhere, and I don't know what's triggering it to happen. Blast furnaces and smokers work fine. Any guidance would be appreciated! 

### Version Information

> lithium-fabric-mc1.19-0.8.1

### Expected Behavior

> Furnaces to smelt properly

### Actual Behavior

> Furnaces stop smelting anything, or they reset their smelting progress. 

### Reproduction Steps

> 1. Place item in furnace, like raw iron.
> 2. Add coal for fuel.
>3. Nothing happens.

#### Server side mods

Additional Additions (Fabric)	- AdditionalAdditions-5.0.1
Architectury API (Fabric/Forge) - architectury-5.10.32-fabric
ARRP - arrp-0.6.2
Artifacts - artifacts-7.1.1+fabric
AttributeFix - AttributeFix-Fabric-1.19-15.0.2
Balm - balm-fabric-4.3.0+0
BCLib - bclib-2.0.16
Better Animals Plus	- betteranimalsplus-1.19-11.0.7-fabric
Better End - better-end-2.0.9
Better Nether - better-nether-7.0.6
Blockus - blockus-2.5.1+1.19
Bluemap - BlueMap-1.7.3-fabric-1.18
Bookshelf - Bookshelf-Fabric-1.19-14.1.7
Building Wands - BuildingWands-2.5.3_mc1.19-fabric
Cardinal Components - cardinal-components-api-5.0.1
Charm - charm-fabric-1.19-4.1.2
Chunky Pregenerator - Chunky-1.2.217
Cloth Config API - cloth-config-7.0.73-fabric
Clumps - Clumps-fabric-1.19-9.0.0+6
Collective (Fabric) - collective-fabric-1.19.x-4.27
Comforts - comforts-fabric-6.0.0-beta.4+1.19
Creeper Overhaul - creeperoverhaul-2.0.1-fabric
Croptopia [FABRIC/FORGE] - Croptopia-1.19-FABRIC-2.0.7
Cycle Paintings - cyclepaintings-fabric_1.19.x-2.3
Death Knell - DeathKnell-Fabric-1.19-4.0.1
Earth2Java - earthtojavamobs-fabric-mc1.19-1.9.2+1.19
Ecologics - ecologics-fabric-1.19-2.1.4
Enchantment Descriptions - EnchantmentDescriptions-Fabric-1.19-11.0.4
Enhanced Mob Spawners - spawnermod-1.19.0-1.2.0+Fabric
Essential Commands - essential_commands-0.26.1-dev02-mc1.19 (was working with the dev with a separate issue, this will be changed with the updated version on CF)
Fabric Enchantments - fabric-enchantments-0.8.0
Fabric Waystones - wraith-waystones-3.0.2+mc1.19
Fabrick Language Kotlin - fabric-language-kotlin-1.8.2+kotlin.1.7.10
Flan - flan-1.19-1.7.10-fabric
GeckoLib - geckolib-fabric-1.19-3.1.6
Goblin Traders - goblin-traders-1.5.2
heyimspook's More Armor & Tools Mod [Forge/Fabric] - smaatm-v2.0.2-mc1.19
Inv View - InvView-1.4.9-1.19+
Inventory Sorting - InventorySorter-1.8.10-1.19
Jade - Jade-1.19-fabric-7.6.0
Just Player Heads (Fabric) - justplayerheads-fabric_1.19.x-2.1
KleeSlabs	- kleeslabs-fabric-1.19-12.0.0
Lithium - lithium-fabric-mc1.19-0.8.1
Lootr (Fabric) - lootr-1.19-0.4.21.60
Lucky Block - lucky-block-fabric-1.19-13.0
Macaw's Paintings - mcw-paintings-1.0.3fabric-mc1.19
Macaw's Paths and Pavings - mcw-paths-1.0.0fabric-mc1.19
MemoryLeakFix - memoryleakfix-1.19-0.5.4
MidnightLib - midnightlib-0.5.2
Minekea - minekea-fabric-1.19-3.2.0
Mining Dimensions - MiningDimensions_Fabric-1.19.1-1.4.19
Mo Glass - Mo-Glass-1.6.1-MC1.19
Mob Catcher - MobCatcher-Fabric-1.19.1-1.2.5
More Axolotl Variants Mod - mavm-1.1.0-mc1.19
More Axolotls - more-axolotls-1.0.2-1.19
More Villagers	- morevillagers-fabric-1.19-4.0.2
Naturalist - naturalist-fabric-2.0.1-1.19
Nature's Compass - NaturesCompass-1.19-2.0.4-fabric
NetherPortalFix - netherportalfix-fabric-1.19-10.0.0
NPC Variety - npc-variety-1.19-2.2.1
Oh The Biomes You'll Go Refabricated - Oh_The_Biomes_You'll_Go-fabric-1.19-2.0.0.7
Patchouli - Patchouli-1.19-74-FABRIC
Phosphor	- phosphor-fabric-mc1.19.x-0.8.1
Plushie Mod - plushie-mod-1.2
Probably Chests - probablychests-0.5.2
Random Bone Meal Flowers (Fabric) - randombonemealflowers-fabric_1.19.x-1.8
Repurposed Structures - repurposed_structures_fabric-6.1.1+1.19
Roughly Enough Items - RoughlyEnoughItems-9.1.517
Scaffolding Drops Nearby - scaffoldingdropsnearby-fabric_1.19.x-1.7
Shoppy (Fabric) - shoppy-fabric-1.19-1.0.3
Shulker Drops Two - shulkerdropstwo-fabric_1.19.x-1.9
Simple Voice Chat - voicechat-fabric-1.19-2.2.52
Sit - sit-1.19-20
SkyLib - skylorlib-1.5.1
Spark - spark-1.9.26-fabric
Stack Refill - stackrefill-fabric_1.19.x-2.2
Stylized Player List - styledplayerlist-2.2.1+1.19
TerraBlender - TerraBlender-fabric-1.19-2.0.0.117
Terraria Paintings - Terraria Paintings Fabric 2.0.0 1.19
Terrarian Slimes - terrarian-slimes-1.3-BETA+1.19
The Graveyard - The_Graveyard_1.10_(FABRIC)_for_1.19
ThonkUtil - thonkutil-2.15.3+1.19
Tokenable Furnaces and Storage - tokenablefurnaces-2.0.1
Too Fast - toofast-1.19-1.0.0
Traveler's Backpack - travelers-backpack-1.19-8.0.2
Tree Harvester (Fabric) - treeharvester-fabric_1.19.x-5.2
Trinkets - trinkets-3.4.0
Wooled Boots - Wooled-Boots-v1.3.1-FABRIC-mc1.19
World Border (Fabric) - worldborder-fabric_1.19.x-2.7
WorldEdit - worldedit-mod-7.2.11-beta-01
Xaero's Minimap - Xaeros_Minimap_22.12.0_Fabric_1.19
Xaero's World Map - XaerosWorldMap_1.26.1_Fabric_1.19
You're in Grave Danger - youre-in-grave-danger-1.4.1
KubeJS - kubejs-fabric-1900.5.5-build.27
Rhino - rhino-fabric-1802.1.14-build.206
LuckPerms - LuckPerms-Fabric-5.4.35
Plan - PlanFabric-5.4-build-1722

#### Client Side Mods

Additional Additions (Fabric) - AdditionalAdditions-5.0.1
Architectury API (Fabric/Forge) - architectury-5.10.32-fabric
Armor Visibility - armor-visibility-5.0.1+1.19-fabric
ARRP - arrp-0.6.2
Artifacts - artifacts-7.1.1+fabric
AttributeFix - AttributeFix-Fabric-1.19-15.0.2
BCLib - bclib-2.0.16
Better Animals Plus - betteranimalsplus-1.19-11.0.7-fabric
Better End - better-end-2.0.9
Better Nether - better-nether-7.0.6
Blockus - blockus-2.5.1+1.19
Bookshelf - Bookshelf-Fabric-1.19-14.1.7
Building Wands - BuildingWands-2.5.3_mc1.19-fabric
Cardinal Components - cardinal-components-api-5.0.1
Charm - charm-fabric-1.19-4.1.2
Charmonium - charmonium-fabric-1.19-4.1.0
Chat Heads - chat_heads-0.6.0-fabric-1.19
Chunky Pregenerator - Chunky-1.2.217
Cloth Config API - cloth-config-7.0.73-fabric
Collective (Fabric) - collective-fabric-1.19.x-4.27
Comforts - comforts-fabric-6.0.0-beta.4+1.19
Controlling - Controlling-fabric-1.19-10.0+2
Creeper Overhaul - creeperoverhaul-2.0.1-fabric
Croptopia [FABRIC/FORGE] - Croptopia-1.19-FABRIC-2.0.7
Cycle Paintings - cyclepaintings-fabric_1.19.x-2.3
Dark Loading Screen - dark-loading-screen-1.6.12
Earth2Java - earthtojavamobs-fabric-mc1.19-1.9.2+1.19
Ecologics - ecologics-fabric-1.19-2.1.4
Enchanting Commands - enchantingcommands-fabric_1.19.x-2.1
Enchantment Descriptions - EnchantmentDescriptions-Fabric-1.19-11.0.4
Enhanced Mob Spawners - spawnermod-1.19.0-1.2.0+Fabric
Fabric Enchantments - fabric-enchantments-0.8.0
Fabric Waystones - wraith-waystones-3.0.2+mc1.19
Fabrick Language Kotlin - fabric-language-kotlin-1.8.2+kotlin.1.7.10
Flan - flan-1.19-1.7.10-fabric
GeckoLib - geckolib-fabric-1.19-3.1.6
Goblin Traders - goblin-traders-1.5.2
heyimspook's More Armor & Tools Mod [Forge/Fabric] - smaatm-v2.0.2-mc1.19
Inventory Sorting - InventorySorter-1.8.10-1.19
Iris Shaders - iris-mc1.19-1.2.5
Jade - Jade-1.19-fabric-7.6.0
Lootr (Fabric) - lootr-1.19-0.4.21.60
Lucky Block - lucky-block-fabric-1.19-13.0
Macaw's Paintings - mcw-paintings-1.0.3fabric-mc1.19
Macaw's Paths and Pavings - mcw-paths-1.0.0fabric-mc1.19
MemoryLeakFix - memoryleakfix-1.19-0.5.4
MidnightLib - midnightlib-0.5.2
Minekea - minekea-fabric-1.19-3.2.0
Mining Dimensions - MiningDimensions_Fabric-1.19.1-1.4.19
Mo Glass - Mo-Glass-1.6.1-MC1.19
Mob Catcher - MobCatcher-Fabric-1.19.1-1.2.5
Mod Menu - modmenu-4.0.4
More Axolotl Variants Mod - mavm-1.1.0-mc1.19
More Axolotls - more-axolotls-1.0.2-1.19
More Villagers - morevillagers-fabric-1.19-4.0.2
Mouse Tweaks - MouseTweaks-fabric-mc1.19-2.22
Naturalist - naturalist-fabric-2.0.1-1.19
Nature's Compass - NaturesCompass-1.19-2.0.4-fabric
NPC Variety - npc-variety-1.19-2.2.1
Oh The Biomes You'll Go Refabricated - Oh_The_Biomes_You'll_Go-fabric-1.19-2.0.0.7
Passive Shield - passiveshield-fabric_1.19.x-2.1
Patchouli  - Patchouli-1.19-74-FABRIC
Plushie Mod - plushie-mod-1.2
Probably Chests - probablychests-0.5.2
Repurposed Structures - repurposed_structures_fabric-6.1.1+1.19
Roughly Enough Items - RoughlyEnoughItems-9.1.517
Scaffolding Drops Nearby - scaffoldingdropsnearby-fabric_1.19.x-1.7
Shoppy (Fabric) - shoppy-fabric-1.19-1.0.3
Simple Voice Chat - voicechat-fabric-1.19-2.2.52
Sit - sit-1.19-20
SkyLib - skylorlib-1.5.1
Sodium - sodium-fabric-mc1.19-0.4.2+build.16
Spark - spark-1.9.26-fabric
TerraBlender - TerraBlender-fabric-1.19-2.0.0.117
Terraria Paintings - Terraria Paintings Fabric 2.0.0 1.19
Terrarian Slimes - terrarian-slimes-1.3-BETA+1.19
The Graveyard - The_Graveyard_1.10_(FABRIC)_for_1.19
ThonkUtil - thonkutil-2.15.3+1.19
Tokenable Furnaces and Storage - tokenablefurnaces-2.0.1
ToolTipFix - tooltipfix-1.0.5-1.19
Traveler's Backpack - travelers-backpack-1.19-8.0.2
Trinkets - trinkets-3.4.0
Wooled Boots - Wooled-Boots-v1.3.1-FABRIC-mc1.19
WorldEdit - worldedit-mod-7.2.11-beta-01
Xaero's Minimap - Xaeros_Minimap_22.12.0_Fabric_1.19
Xaero's World Map - XaerosWorldMap_1.26.1_Fabric_1.19
You're in Grave Danger - youre-in-grave-danger-1.4.1
Zoomify - Zoomify-1.7.1
KubeJS - kubejs-fabric-1900.5.5-build.27
Rhino - rhino-fabric-1802.1.14-build.206
No Angled Brackets - no_angled_brackets-1.19-1.0.1-fabric
FlytreLib - flytre_lib-1.19-1.8.8-fabric

**Comment by kingstairs** [comment] 2022-07-28 21:28
Unfortunately a large mod list can make diagnosis difficult, especially if two unrelated mods are interacting triggering this. I'd specifically focus on mods that impact crafting/transforming (e.g., smelters), such as maybe _Tokenable Furnaces and Storage_?

1. For testing, I'd suggest starting with an new MC instance without any mods (server/client), make sure smelting works.
2. Then start adding mods (and their dependencies) - _client-side only_ - one at a time, until the problem re-occurs.
4. If that doesn't trigger the problem, then try adding the server-side mods.

I'm using quite a few of the (client-side) mods on your list, so when testing probably leave Xaero, kwpugh mods until last as I'm reasonably confident they're not the cause.

Hope that helps a little?

**Comment by 2No2Name** [comment] 2022-07-28 22:42
If the items are in the furnace inventory, the issue is likely to not be caused by lithium. If the items aren't transferred into the furnace with hoppers, or it only works when the player transfers the items manually, lithium might have to do something with this

**Comment by 2No2Name** [comment] 2022-08-07 21:39
I suggest you try removing half of the mods at a time to find a minimal set of monds that is required for the issue to occur within a few attempts

**Closed as completed** 2022-12-24 00:16 UTC
