### ISSUE TITLE
Mob ai not working, so mobs sometimes don't move and only look around.

### ISSUE THREAD

**Issue by BothFalcon** [jellysquid3/Lithium#99] opened 2020-08-07 15:51 UTC
### Expected Behavior
Mobs should be moving around, but they only stay and look around. Creepers in my farm sometimes run a from cats.

### Actual Behavior
Mobs just stay and look around

Example: Pigs stay and look around.

**Comment by 2No2Name** [comment] 2020-08-07 16:56
I cannot reproduce this issue. In singleplayer in specator mode mobs don't move, but that is also in vanilla. When the player is in creative mode the mobs seem to move without issues.

**Comment by Suya1671** [comment] 2020-08-09 17:23
I've been able to reproduce this on my server, by accident. Its very annoying if you have gunpowder and gold farms

**Comment by 2No2Name** [comment] 2020-08-09 21:20
Can you give me the farm design (worlddownload, video link, whatever)?

**Comment by Suya1671** [comment] 2020-08-10 08:16
Gold farm: https://www.youtube.com/watch?v=e8fkpET5fOI

Gunpowder: https://www.youtube.com/watch?v=F73QtCeeQ40

**Comment by OS-Void** [comment] 2020-08-10 09:21
I use the gunpowder one on my server and it works fine, although I'm using latest commits oppose to latest release.

**Comment by Suya1671** [comment] 2020-08-10 09:23
I use aternos so i cant use latest commit. See if you get the bug on latest release.

**Comment by Suya1671** [comment] 2020-08-10 09:24
I could also send the world & modpack download

**Comment by Kurumi78** [comment] 2020-08-14 07:38
I would download the world and check if it happens with the mods on a local server/singleplayer, Aternos server performance could be causing problems.

**Comment by Suya1671** [comment] 2020-08-15 17:51
This farm does work on a normal vanilla server, ill check the world soon ;)

**Comment by 2No2Name** [comment] 2020-08-21 11:22
I tested a cat based creeper farm (very similar to the video) and had no problems.

**Comment by ghost** [comment] 2020-08-30 02:11
/player gold spawn at -7.30 250.19 -11.55 facing -90 0
/gamemode survival gold
/summon minecraft:zombified_piglin -4.30 250.50 -11.43
/player gold attack
/tick warp 2000
/player gold kill
/player gold spawn at -7.30 250.19 -11.55 facing -90 0
/gamemode survival gold
/tick warp 20000

Should be able to observe pigmen break aggro, the longer time progresses the more pigmen lose aggro
Tested 1.16.2 with lithium 0.5.2
[rayworks gold barter farm.zip](https://github.com/jellysquid3/lithium-fabric/files/5146252/rayworks.gold.barter.farm.zip)

**Comment by jellysquid3** [comment] 2020-08-31 06:16
Marking as confirmed as this issue has been reported by multiple players.

**Comment by 2No2Name** [comment] 2020-09-15 17:33
Does adding
```
mixin.ai.goal=false
mixin.ai.nearby_entity_tracking=false
mixin.ai.pathing=false
mixin.ai.poi=false
mixin.ai.raid=false
mixin.ai.task=false

```
 to the lithium.properties resolve the problem?

**Comment by ghost** [comment] 2020-09-15 19:32
Upon further testing, this will occur without lithium. Is most likely a vanilla bug then.

**Comment by jellysquid3** [comment] 2020-09-18 16:54
Upon further discussion on the Discord and the user update here, this appears to be a problem in vanilla and is not within the scope of Lithium for us to fix.

**Closed as completed by jellysquid3** 2020-09-18 16:54 UTC
Labels: T-bug, E-external
