### ISSUE TITLE
Lithium crashes via mob spawning optimization.

### ISSUE THREAD

**Issue by Kichura** [jellysquid3/Lithium#169] opened 2020-11-20 13:29 UTC
### Reproduction Steps
When lithium is (likely) combined with the lambdynamiclights mod + Config set so that the mob spawning mixin is set to true, Creating a new world singleplayer and exploring a bit has a low chance of crashing the game based of entity ticks from throwing eggs, Waiting for specific mob to spawn that has corrupted/broken health with it, etc.

1. Install lithium + lambdynamiclights mods to a new fabric profile (Or use my own modpack if capable),
2. Set the mixin "mixin.world.mob_spawning" to true via lithium properties,
3. Create a new world in singleplayer and start exploring for a while,
4. Game may likely crash based of broken health or other entity tick trigger.

### Crash Report File
[lithium_crash.log](https://github.com/jellysquid3/lithium-fabric/files/5573740/lithium_crash.log)

### Additional Information
This crash seems to be rare in some conditions as only few units have been getting this issue along, Although it seems that this crash is trying to "blame lambdynamiclights for it" aswell but i just can't seem to confirm it.

This crash also seems to be targeting other entities aswell such as pigs and whatnot.

**Comment by 2No2Name** [comment] 2020-11-20 19:19
Your crashreport contains a method from multiconnnect. Try disabling mixin.entity.data_tracker.use_arrays

**Comment by Earthcomputer** [comment] 2020-11-21 17:49
Multiconnect automatically disables that 2no, and has done for a while.
This looks like https://github.com/Earthcomputer/multiconnect/issues/93, which has nothing to do with lithium. It is however interesting that your setup is making the issue more reproducible. Could you add a comment to the multiconnect issue about this?

**Comment by jellysquid3** [comment] 2021-01-02 06:09
I'm going to go ahead and close this issue as it appears to happen independently of having Lithium installed.

**Closed as completed by jellysquid3** 2021-01-02 06:09 UTC
Labels: E-external
