### ISSUE TITLE
Well... unexpected crash

### ISSUE THREAD

**Issue by K0-RR** [jellysquid3/Lithium#163] opened 2020-11-12 11:49 UTC
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2020-11-12 12:44:26 CET
Description: Exception while ticking

java.lang.IllegalArgumentException: Cannot set property class_2758{name=level, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} to 1 on net.minecraft.class_3621$class_3622@7d561f0, it is not an allowed value
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.1)
    at net.minecraft.state.State.with(State:122)
    at net.minecraft.fluid.FlowableFluid.getFlowing(FlowableFluid:243)
    at net.minecraft.fluid.FlowableFluid.getUpdatedState(FlowableFluid:205)
    at net.minecraft.fluid.FlowableFluid.getSpread(FlowableFluid:373)
    at net.minecraft.fluid.FlowableFluid.method_15744(FlowableFluid:153)
    at net.minecraft.fluid.FlowableFluid.tryFlow(FlowableFluid:140)
    at net.minecraft.fluid.FlowableFluid.onScheduledTick(FlowableFluid:458)
    at net.minecraft.fluid.FluidState.onScheduledTick(FluidState:72)
    at net.minecraft.server.world.ServerWorld.tickFluid(ServerWorld:595)
    at net.minecraft.class_3218$$Lambda$4508/000000000000000000.accept(Unknown Source)
    at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.executeTicks(LithiumServerTickScheduler.java:227)
    at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.tick(LithiumServerTickScheduler.java:73)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:358)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
    at net.minecraft.server.MinecraftServer.handler$bmh000$modifiedRunLoop(MinecraftServer:7310)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at net.minecraft.server.MinecraftServer$$Lambda$4489/000000000000000000.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:836)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block being ticked --
  Block location: World: (-2363,11,-1239), Chunk: (at 5,0,9 in -148,-78; contains blocks -2368,0,-1248 to -2353,255,-1233), Region: (-5,-3; contains chunks -160,-96 to -129,-65, blocks -2560,0,-1536 to -2049,255,-1025)

-- Affected level --
  All players: 1 total; [class_3222['_K0RR_'/242, l='ServerLevel[New World9]', x=-2215.61, y=32.00, z=-1237.96]]
  Chunk stats: ServerChunkCache: 9555
  Level dimension: minecraft:overworld
  Level spawn location: World: (15,86,184), Chunk: (at 15,5,8 in 0,11; contains blocks 0,0,176 to 15,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 6653 game time, 6653 day time
  Level name: New World9
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
  Level weather: Rain time: 44814 (now: false), thunder time: 31201 (now: false)
  Known server brands: fabric
  Level was modded: true
  Level storage version: 0x04ABD - Anvil

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.4.70-amd64-desktop
  Java Version: 11.0.9, AdoptOpenJDK
  Java VM Version: Eclipse OpenJ9 VM (JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
                   OpenJ9   - 0394ef754
                   OMR      - 582366ae5
                   JCL      - 3b09cfd7e9 based on jdk-11.0.9+11), Eclipse OpenJ9
  Memory: 4153433912 bytes (3961 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 8
  JVM Flags: 5 total; -Xoptionsfile=/home/k0rr/Downloads/jdk-14.0.2+12/lib/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xms8192m -Xmx8192m
  Suspected Mods: Lithium (lithium)
  Fabric Mods: accurateblockplacement: Accurate Block Placement 1.0.7
               adorn: Adorn 1.12.0+1.16.4
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               artifice: Artifice 0.13.1+1.16.2-rc1
               astromine: Astromine 1.11.4+fabric-1.16.3
               astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
               astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
               astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
               astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
               astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
               atmosfera: Atmosfera 1.3.5
               authme: Auth Me 1.4.0
               autoconfig1u: Auto Config v1 Updated 3.2.2
               autoswap: Autoswap 1.16.2-fabric0.17.2-1.0.1
               battletowers: Battle Towers 3.2.0-beta-1.16.4
               bedrockify: BedrockIfy 0.1.9
               bendy-lib: Bendy api 0.2.3
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               betternether: Better Nether 5.0.0
               betterstones: Better Stones 0.0.4
               blade: Blade 2.0.0
               blue_endless_jankson: jankson 1.2.0
               byg: BYG 1.1.2
               campanion: Campanion 1.2.0+build.39
               cardinal-components-base: Cardinal Components API (base) 2.7.1
               cardinal-components-block: Cardinal Components API (blocks) 2.6.0
               cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
               cardinal-components-entity: Cardinal Components API (entities) 2.7.1
               cardinal-components-item: Cardinal Components API (items) 2.6.0
               cardinal-components-level: Cardinal Components API (world saves) 2.6.0
               cardinal-components-util: Cardinal Components API (utilities) 2.6.0
               cardinal-components-world: Cardinal Components API (worlds) 2.6.0
               carpet: Carpet Mod in Fabric 1.4.12
               cavebiomes: Cave Biomes 0.5.1
               charm: Charm 2.1.1
               charmonium: Charmonium 2.0.2
               chat_heads: Chat Heads 0.2.0+1.16.2
               chesttracker: Chest Tracker 0.7.9
               chunkpregen: Fabric Chunk Pregenerator 0.3.3
               cinderscapes: Cinderscapes 1.2.4+build.43-1.16.4
               climbable: Climbable 0.2.0
               cloth-api: Cloth API 1.4.9
               cloth-armor-api-v1: Cloth Armor API v1 1.4.9
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-common-events-v1: Cloth Common Events v1 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
               cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
               cloth-utils-v1: Cloth Utils v1 1.4.9
               com_electronwill_night-config_core: core 3.6.2
               com_electronwill_night-config_toml: toml 3.6.2
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               com_typesafe_config: config 1.4.0
               commandaliases: Command Aliases 0.1.5
               computercraft: CC:T for Fabric 1.91.2
               couplings: Couplings 1.3.3
               crimsonmoon: Crimson Moon 1.2.3-1.16.2
               croptopia: Croptopia 1.0.4-1.16.3-FABRIC
               crowdin-translate: CrowdinTranslate 1.2
               crumbs: Crumbs 1.0.2+1.16.4-fabric
               custom-fog: Custom Fog 1.2.0
               customportals: Custom Portals 1.3.0
               customstars: Custom Stars 0.4.1
               dawn: Dawn API 1.5.3
               deadtotems: Dead Totems 0.1.1+1.16.3
               dehydration: Dehydration 1.0.8
               dishes: Delicious Dishes 2.0.0
               dungeons_of_exile: Dungeons of Exile 1.1.1
               durabilityviewer: Giselbaers Durability Viewer 1.16.4-fabric0.25.1-1.9
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               easierenchanting: Easier Enchanting 1.4.0
               elytra-recipe: Elytra Recipe 1.0.1
               em: Simple Emerald Mod 1.0.0
               emerald_tools: Emerald Tools 1.0.39
               emotecraft: Emotecraft 1.2.1
               environmentz: EnvironmentZ 1.0.5
               expandedconcrete: Expanded Concrete 0.0.2
               fabric: Fabric API 0.25.4+1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
               fabrication: Fabrication 1.2.3_01
               fabricloader: Fabric Loader 0.10.6+build.214
               fairenchanting: FairEnchanting 1.2.0
               fallflyinglib: FallFlyingLib 1.1.0
               falling_tree: FallingTree 2.6.0
               fallingleaves: Falling Leaves 1.1
               fermion: Fermion 2.1.191
               fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
               fiber: fiber 0.23.0-2
               flight_rings: Flight Rings 1.4.2
               gbfabrictools: GBfabrictools 1.3.2+1.16.4
               glassdoor: Glass Doors 1.5.0-1.16
               gravestones: Gravestones 1.5
               grindenchantments: Grind Enchantments 1.1.3+1.16.3
               headsdowndisplay: Heads down display 0.0.0
               images: Images 0.3.1+1.16.3
               inventoryhud: Inventory HUD + 3.1.3
               invview: InvView 1.1.0-1.16.2+
               jankson: Jankson 3.0.1+j1.2.0
               javax_vecmath_vecmath: vecmath 1.5.2
               lakeside: Lakeside 1.0.3+1.16.4
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               lapisreserve: Lapis Reserve 1.0.6
               libblockattributes_core: LibBlockAttributes (Core) 0.8.2
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.2
               libblockattributes_items: LibBlockAttributes (Items) 0.8.2
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.2.1+1.16.3
               library_of_exile: Library of Exile 1.0.6
               libstructure: LibStructure 1.5
               lightstones: Lightstones 1.2
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               maelstrom_library: Maelstrom Library 0.4.1
               magna: Magna 1.4.3-1.16.2
               mambience: MAmbience 2.1.0+1.16.2
               microdurability: microDurability 0.2.0+1.16.3
               midnight-hats: Midnight Hats 2.0.0
               minecraft: Minecraft 1.16.4
               minegate-moreblocks: MineGate - MoreBlocks 1.0.1
               minimaltweaks: Minimal Tweaks 1.0.3
               mixedslab: Mixed Slab 1.16.3-1.2
               mm: Manningham Mills 2.1
               mobs_attempt_parkour: Mobs Attempt Parkour 0.2.1-1.16.3
               modmenu: Mod Menu 1.14.8+build.12
               modupdater: ModUpdater 1.1.11+1.16.2-rc2
               more_gems: More Gems 1.1.7
               moreblocksmod: More Blocks Mod 1.0.0
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
               mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
               mousewheelie: Mouse Wheelie 1.5.9+mc1.16.4
               mythicmetals: Mythic Metals 0.9.4
               namepain: Name Pain 1.3.1
               nbtcrafting: NBT Crafting 2.0.1+mc1.16.4
               nookbuild: NookBuild 1.2.1
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               nourish: Nourish 1.1.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_aeonbits_owner_owner: owner 1.0.12
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_joml_joml: joml 1.9.25
               origins: Origins 0.4.4
               patchouli: Patchouli 1.16.2-44-FABRIC
               phosphor: Phosphor 0.6.0+build.7
               photoallergiccreepers: Photoallergic Creepers 0.2.0+1.16.1
               piglib: Piglib 1.0.1
               playerabilitylib: Pal 1.2.1
               polymorph: Polymorph 0.0.5-1.16.3
               rare-ice: Rare Ice 0.2.2
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               repurposed_structures: Repurposed Structures 1.16.3-1.6.9
               ringsofascension: Rings of Ascension 1.1.1
               rocks: This Rocks! 1.1.0
               roughlyenoughitems: Roughly Enough Items 5.8.3
               roughlyenoughitems-api: REI (API) 5.8.3
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.3
               roughlyenoughitems-runtime: REI (Runtime) 5.8.3
               rpgstats: RPGStats 2.3.2+1.16.3
               satin: Satin 1.4.1
               seasons: Fabric Seasons 0.3-BETA
               shapes: Shapes 2.0.0+build.10
               simpleteleporters: Simple Teleporters 2.2.1
               slight-gui-modifications: 'Slight' GUI Modifications 1.5.1
               slyde: Slyde 1.1
               snowdrift: Snowdrift ${version}
               snowy_leaves: Snowy Leaves 1.16.1-1.3.1
               soaring-clouds: Soaring Clouds 1.2.0-1.16
               sodium: Sodium 0.1.0
               spiceoffabric: Spice of Fabric 1.2.6+1.16.3
               splash: Splash 1.1.1
               spruceui: SpruceUI 1.6.4
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               stepup: StepUp 1.16.4-fabric0.25.1-1.1
               structure-helpers: Structure Helpers 3.0.0
               team_reborn_energy: Energy 0.1.0
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               terrestria: Terrestria 2.1.4+build.26
               tinytweaks: TinyTweaks 1.0.15
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               traverse: Traverse 3.0.1+build.8
               trinkets: Trinkets 2.6.7
               trunk: TRUNK 0.1.0
               tweed: Tweed API 3.0.0-beta.18
               unearthed: Unearthed 1.0.5
               vanilla-toolsets: Vanilla Toolsets 1.3.0
               vanillaenhanced: VanillaEnhanced 1.3.1
               visp: Visp 0.0.3
               voxelmap: VoxelMap 1.10.11
               voyager: Voyager 1.0.0
               walljump: Wall-Jump! 1.3.3+1.16.1
               water-erosion: Water Erosion 1.1.1
               waystones: Waystones 1.0.9
               wild_explorer: Wild Explorer 1.2.1
               wildworld: Wild World 1.3.0+1.16.2
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               woodsplus: Woods Plus 0.0.2
               worldedit: WorldEdit 7.2.0-rc-01+81f978e
               worldtime: WorldTime 1.16.4-fabric0.25.1-1.2.4
               wrenchable: Wrenchable 1.0.0+1.16.1
               xaerominimap: Xaero's Minimap 20.27.2
               xpstorage: XP Storage 1.1.1+1.16.4
  Patchouli open book context: n/a
  Player Count: 1 / 8; [class_3222['_K0RR_'/242, l='ServerLevel[New World9]', x=-2215.61, y=32.00, z=-1237.96]]
  Data Packs: vanilla, fabric/deadtotems, fabric/trinkets, fabric/betternether, fabric/dehydration, fabric/astromine-discoveries, fabric/astromine-transportations, fabric/astromine-foundations, fabric/morecraftingtables, fabric/repurposed_structures, fabric/battletowers, fabric/structure-helpers, fabric/mostructures, fabric/origins, fabric/adorn, fabric/vanillaenhanced, fabric/charm, fabric/terrestria, fabric/expandedconcrete, fabric/tinytweaks, fabric/seasons, fabric/wolveswitharmor, fabric/elytra-recipe, fabric/em (incompatible), fabric/crumbs, fabric/moreblocksmod, fabric/xpstorage, fabric/mixedslab, fabric/emerald_tools (incompatible), fabric/vanilla-toolsets, fabric/croptopia, fabric/gravestones, fabric/byg, fabric/cinderscapes, fabric/flight_rings, fabric/customportals, fabric/mythicmetals, fabric/dungeons_of_exile (incompatible), fabric/rpgstats, fabric/piglib, fabric/nookbuild, fabric/images, fabric/betterstones, fabric/wild_explorer, fabric/fabric-tool-attribute-api-v1, fabric/rare-ice (incompatible), fabric/unearthed, fabric/nourish, fabric/dishes, fabric/computercraft (incompatible), fabric/astromine-technologies, fabric/woodsplus, fabric/bedrockify, fabric/lightstones, fabric/environmentz, fabric/libcd, fabric/cavebiomes, fabric/simpleteleporters, fabric/waystones, fabric/campanion, fabric/minimaltweaks, fabric/glassdoor, fabric/traverse, fabric/wildworld, fabric/more_gems, fabric/rocks, fabric/spiceoffabric, fabric/astromine-core, fabric/minegate-moreblocks (incompatible)
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by 2No2Name** [comment] 2020-11-12 12:21
Can you test whether the issue occurs when lithium is not installed?

**Comment by jellysquid3** [comment] 2020-11-19 23:43
Closing as duplicate of #164.

**Closed as completed by jellysquid3** 2020-11-19 23:43 UTC
Labels: E-duplicate
