### ISSUE TITLE
Game crashes when

### ISSUE THREAD

**Issue by amethyst-87** [jellysquid3/Lithium#529] opened 2024-06-28 12:36 UTC
Game just crashes randomly, probably when someone dies. Checked the logs and it said something about Lithium.
Tested it without Lithium and it did not crash
Logs:
https://mclo.gs/3PfAvp7

**Comment by 2No2Name** [comment] 2024-06-29 16:54
Duplicate of #527

**Closed as not planned** 2024-06-29 16:55 UTC
