### ISSUE TITLE
HopperHelper Mixin from Carpet Essentials & Carpet TIS Addions Crash

### ISSUE THREAD

**Issue by TinyDerp** [jellysquid3/Lithium#553] opened 2024-08-15 17:36 UTC
### Version

>lithium-fabric-mc1.21-0.13.0.jar
### Reproduction Steps

> 1. Activate the server
> 2. Join server
> 3. Crash
### Crash Report File

>[crash-2024-08-15_20.15.03-server.txt](https://github.com/user-attachments/files/16627982/crash-2024-08-15_20.15.03-server.txt)
>[crash-2024-08-15_20.08.08-server.txt](https://github.com/user-attachments/files/16627981/crash-2024-08-15_20.08.08-server.txt)
### Minecraft Save

>[a32xse.zip](https://files.catbox.moe/a32xse.zip)
### Additional Information

It seams that [Carpet Essentials](https://modrinth.com/mod/essentialaddons) & [Carpet TIS Addions](https://modrinth.com/mod/carpet-tis-addition) don't work with lithium at all on the newer minecraft versions. Something to do with hoppers and other containers. 
Hope there's going to be a fix soon.

**Comment by Lolothepro** [comment] 2024-08-15 17:38
duplicate of 521 ?

**Comment by 2No2Name** [comment] 2024-08-15 17:44
Not a duplicate, but this needs to be fixed on their side

**Comment by 2No2Name** [comment] 2024-08-15 17:47
Please report this to Carpet Essentials and Carpet TIS Additions

**Closed as not planned** 2024-08-15 17:47 UTC
