### ISSUE TITLE
Zombie in minecart not moving in flowing water

### ISSUE THREAD

**Issue by cschierig** [jellysquid3/Lithium#153] opened 2020-10-16 20:08 UTC
### Expected Behavior

The zombie should move around, pushed by the flowing water.

### Actual Behavior

The zombie just stays at one position

### Reproduction Steps

I've found the issue in the world download of Gnembons most recent iron farm video (<https://www.youtube.com/watch?v=_O6q53zmCMY>). The zombies in the minecarts don't move in version 1.16.3.

**Comment by amnotbananaama** [comment] 2020-10-16 20:12
This was fixed in version [0.5.6](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.3-0.5.6) for 1.16.3, can you confirm you are running that version? Otherwise this issue is a duplicate of #144

**Comment by cschierig** [comment] 2020-10-16 21:00
I'm pretty sure I am running the newest version, but I'll look again tomorrow.

**Comment by cschierig** [comment] 2020-10-17 09:19
My bad. I was using version 0.5.5. Thanks anyways

**Closed as completed** 2020-10-17 09:19 UTC
Labels: T-bug
