### ISSUE TITLE
After using the 0.7.4 version of lithium, litematica cannot see the switched rendering layer in real time

### ISSUE THREAD

**Issue by PiPiSenLetsGo** [jellysquid3/Lithium#276] opened 2021-09-05 03:19 UTC
### Version Information
>lithium-fabric-mc1.17.1-0.7.4

### Actual Behavior

> Use [litematica-fabric-1.17.1-0.0.0-dev.20210713.103711](https://www.curseforge.com/minecraft/mc-mods/litematica/files/3387062)

> Use 0.7.3 version lithium, litematica works normally.
> After using 0.7.4 version  lithium, litematica cannot see the switched rendering layer in real time.

> It is normal when the rendering mode is all. Switch the rendering mode to single layer, above or below. When switching the rendering layer (for example, y=80 to y=81), the projection still displays the original rendering layer (y=80). You need to switch back to all and then to single layer to display the correct rendering layer (y=81).
> The same problem occurs when the rendering mode is above or below.

### Other Information

> fabric loader version: 0.11.6
> fabric-api-0.40.0+1.17
> sodium-fabric-mc1.17.1-0.3.2+build.7
> malilib-fabric-1.17.1-0.10.0-dev.24
> starlight-1.0.0-RC3+fabric.1.17.x

**Comment by koopaboopa** [comment] 2021-09-06 02:48
I believe masa (developer of Litematica) has already fixed this issue on Litematica's most recent builds. He hasn't publicly released them yet, but has dev versions on his website. Here's a post in the Scicraft Discord server about it: https://discord.com/channels/211786369951989762/453662800460644354/882950442408103967

**Comment by 2No2Name** [comment] 2021-09-25 16:12
Duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/254

**Closed as completed** 2021-11-05 18:04 UTC
Labels: T-bug, E-external
