### ISSUE TITLE
java.lang.ClassCastException I Ticking entity

### ISSUE THREAD

**Issue by TheButterbrotMan** [jellysquid3/Lithium#330] opened 2021-12-28 21:52 UTC
### Version

> Lithium 0.7.6
### Reproduction Steps

> Random

### Crash Report File
https://pastebin.com/JAwqZ4um

### Additional Information

https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment] 2021-12-28 21:54
Probably linked to #329

**Comment by 2No2Name** [comment] 2021-12-28 22:03
Duplicate of #329

**Closed as completed by 2No2Name** 2021-12-28 22:03 UTC
