### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by xIGBClutchIx** [jellysquid3/Lithium#363] opened 2022-05-17 16:13 UTC
Was playing on public popular server Wynncraft and getting a ticking entity crash. I do have a few other optimization and gameplay mods working with it but seems like the crash is directly related to Lithium.

Version: lithium-fabric-mc1.18.2-0.7.9
Fabric API: fabric-api-0.51.1+1.18.2

Crash Report: [crash-2022-05-17_12.05.38-client.txt](https://github.com/CaffeineMC/lithium-fabric/files/8709892/crash-2022-05-17_12.05.38-client.txt)

**Comment by 2No2Name** [comment] 2022-05-18 18:38
Relates to https://github.com/CaffeineMC/lithium-fabric/issues/356

**Comment by AngelofWoe** [comment] 2022-07-09 20:26
We just had one of these today.
[crash-2022-07-09_18.23.04-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/9077853/crash-2022-07-09_18.23.04-server.txt)

**Comment by limelambda** [comment] 2022-07-13 13:42
Also playing Wynncraft ticking entity crash
https://crashy.net/A12saXgNKU1tNuFbJrxd
https://bytebin.lucko.me/LbRWSOAJaA

**Comment by 2No2Name** [comment] 2022-10-08 18:34
> We just had one of these today. [crash-2022-07-09_18.23.04-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/9077853/crash-2022-07-09_18.23.04-server.txt)

This is unrelated to this issue

**Comment by 2No2Name** [comment] 2022-10-08 18:35
Duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/356 , suggested solutions are posted there.

**Closed as completed by 2No2Name** 2022-10-08 18:35 UTC
