### ISSUE TITLE
Inconistancy of clipped minecart collisions with vanilla

### ISSUE THREAD

**Issue by Alugia7** [jellysquid3/Lithium#143] opened 2020-09-22 17:34 UTC
### Expected Behavior
See video:
https://www.youtube.com/watch?v=j38Zq2efmi8
The minecart clipped in this setup stays clipped into the cauldron and solid block when the top piston is moved

### Actual Behavior
See video: 
https://www.youtube.com/watch?v=IRpEAyyxW3A
The minecart does not properly clip into the solid block and instead falls through it.

### Reproduction Steps

1. Perform clip shown in video
2. Power the top piston which would move the cauldron
3. Minecart isnt clipped into solid block with lithium, which is inconsistent with vanilla

**Comment by 2No2Name** [comment] 2020-09-22 22:35
This is probably caused by the custom voxel shape implementation for voxelshapes that are 1/8th aligned not returning the point positions when combineAndSimplify is called.

**Comment by jellysquid3** [comment] 2020-09-23 15:01
Fixed in [Lithium 0.5.6](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.3-0.5.6).

**Closed as completed by jellysquid3** 2020-09-23 15:01 UTC
Labels: T-bug, S-confirmed
