### ISSUE TITLE
Ticking entity | java.lang.ClassCastException: class net.minecraft.class_1542 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1542 and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @79351f41)

### ISSUE THREAD

**Issue by Nekkok** [jellysquid3/Lithium#329] opened 2021-12-28 15:16 UTC
### Version
> lithium-fabric-mc1.18.1-0.7.6

### Reproduction Steps
> Unknown

### Additional Information

I can't tell what has happened. I was standstill testing some config mods on the overworld and then this happened. Something related points to snowpowder / brownwool / entity.

[crash-2021-12-28_15.49.34-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/7785277/crash-2021-12-28_15.49.34-server.txt)

**Comment by 2No2Name** [comment] 2021-12-28 15:35
Some mod is adding PowderSnowBlock::checkStick which seems to be broken. I don't think this has to do anthing with lithium

**Comment by Nekkok** [comment] 2021-12-28 15:40
Ok, gonna mess up deleting some mods

**Comment by TheButterbrotMan** [comment] 2021-12-28 21:55
> Ok, gonna mess up deleting some mods

Did you find an solution?

**Comment by 2No2Name** [comment] 2021-12-28 22:03
You could install a mod like https://minecraft.curseforge.com/projects/not-enough-crashes to find out which mod is adding that powder snow bug

**Comment by TheButterbrotMan** [comment] 2021-12-28 22:06
https://pastebin.com/JAwqZ4um

Is installed, i still dont know.

**Comment by 2No2Name** [comment] 2021-12-28 22:51
I think it is probably one of these:

		betterbeds: Better Beds 1.2.0
		cloth-api: Cloth API 2.0.54
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dual_riders: DualRiders 1.0.5
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fiber: fiber 0.23.0-2
		libcd: LibCapableData 3.0.3+1.16.3
		libninepatch: LibNinePatch 1.1.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1

**Comment by 2No2Name** [comment] 2021-12-28 23:29
Can you try using this mixintrace mod? https://github.com/comp500/mixintrace/releases/tag/1.1.0%2B1.17 and post the crash report again. A discord users says it also works with 1.18.1

**Comment by LunexLunertic** [comment] 2022-01-01 07:11
Well after reading this post I too was having the same problem with powder snow bug, though in my case it had to do with Gunpowder instead of primed TNT. Am completely unsure if it has anything to do with lithium and after using the mod mixintrace as attempted after reading this thread, it appears to have failed to find the issue, I also have Not Enough Crashes installed as well.

[crash-2021-12-31_22.53.02-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/7797434/crash-2021-12-31_22.53.02-server.txt)

And, after looking at the lists of mods that I have and comparing to his, I believe the cause is by the mod: Hiking Pole for fabric as after I read this for a while and removed that mod the world was working just fine (in a playable state) again as shown here:

[latest.log](https://github.com/CaffeineMC/lithium-fabric/files/7797441/latest.log)

So, I do believe it was that mod "Hiking Pole" that was causing the problem.

**Comment by TheButterbrotMan** [comment] 2022-01-07 00:09
I will try to remove HikingPole, hopefully it works then.

**Comment by TheButterbrotMan** [comment] 2022-01-07 00:12
@2No2Name I think you can close this.

**Comment by 2No2Name** [comment] 2022-01-07 00:22
Issue likely to be handled at https://www.curseforge.com/minecraft/mc-mods/hiking-pole-fabric#c8

**Comment by 2No2Name** [comment] 2022-01-07 00:24
I don't think this is a mod compatibility problem. If there is any testing with Hiking Pole but without Lithium, please share your results as well

**Closed as completed** 2022-01-09 17:09 UTC
Labels: E-external
