### ISSUE TITLE
Crash with ReplayMod

### ISSUE THREAD

**Issue by kesu1** [jellysquid3/Lithium#9] opened 2019-12-23 14:15 UTC
When starting the mod with Replay Mod in 1.14.4, it doesn't even load to the menu, just says "An unexpected error occured..."

**Comment by silversquirl** [comment] 2019-12-23 14:17
If you can provide a log, that'd be a big help with diagnosing the issue

**Comment by kesu1** [comment] 2019-12-23 14:23
[output_log.txt](https://github.com/jellysquid3/Lithium/files/3995243/output_log.txt)

**Comment by jellysquid3** [comment] 2019-12-24 04:23
This issue is caused by the `client.reduceCuboidTransformations` patch. It's not likely it can ever be resolved without disabling this patch. However, I'm looking into creating a hints system to Lithium so we can detect incompatibilities like this and automatically adjust our configuration.

**Comment by jellysquid3** [comment] 2020-01-29 19:47
This patch has since been removed in Minecraft 1.15+.

**Closed as completed by jellysquid3** 2020-01-29 19:47 UTC
