### ISSUE TITLE
Item entities in Create Ponder menus crash with Lithium

### ISSUE THREAD

**Issue by anonezumi** [jellysquid3/Lithium#460] opened 2023-03-23 03:13 UTC
### Version

lithium-fabric-mc1.19.2-0.11.0

### Reproduction Steps

1. Hover over an item such as a Millstone or an Encased Fan (there are several items that can trigger this, but not all create items)
2. Ponder the item using Create's Ponder feature
3. Watch the Ponder scene until an item entity appears on screen
4. Game will crash

### Crash Report File

https://pastebin.com/mbCLPewT

### Additional Information

When uninstalling Lithium, the crash does not occur and Ponder works as normal.

This issue could be related to an issue reported to Create: [Create #4142](https://github.com/Creators-of-Create/Create/issues/4142), but that issue was identified as being caused by another mod.

**Comment by 2No2Name** [comment] 2023-03-23 12:18
Duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/455

**Closed as completed by 2No2Name** 2023-03-23 12:18 UTC
