### ISSUE TITLE
Tnt dropped into water is to lazy to move [just stays were it landed]

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#147] opened 2020-09-28 12:23 UTC
This bug applies For lithium-fabric-mc1.16.3-0.5.5 ( maybe also others but i havent tested that )

### Expected Behavior
tnt landing in water will get pushed by water.
Dispensed tnt is a bit weird tho bc sometimes it works and the tnt gets flushed and sometimes not.

### Actual Behavior
named tnt stays at the landing spot

### Reproduction Steps

take these setups (build any tnt duper) place water a few blocks below and activate the dupers.
or place a tnt in a water stream and activate it (2nd picture).
in case you dont know ho to propperly build tnt dupers maybe search on youtube it makes no difference wich you use.

![2020-09-28_14 05 18](https://user-images.githubusercontent.com/72020192/94430314-f52b2d80-0193-11eb-8bd7-5ebefe7b2a05.png)
![2020-09-28_13 54 56](https://user-images.githubusercontent.com/72020192/94430317-f65c5a80-0193-11eb-84f9-b274f08b11df.png)
![2020-09-28_13 54 14](https://user-images.githubusercontent.com/72020192/94430318-f6f4f100-0193-11eb-8c63-c43588d92ac3.png)
![2020-09-28_13 54 08](https://user-images.githubusercontent.com/72020192/94430320-f78d8780-0193-11eb-8d0c-1a8cf47611fc.png)

**Comment by LucilleTea** [comment] 2020-09-28 12:25
Duplicate of #144, [fixed in Lithium 0.5.6](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.3-0.5.6).

**Closed as completed** 2020-09-29 12:43 UTC
Labels: T-bug
