### ISSUE TITLE
Crash With Optifine On World Load in 1.16.1

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#72] opened 2020-07-04 01:49 UTC
### Reproduction Steps
Run fabric with mods: 
 - optifine (1.16.1-pre2)
 - optifabric (1.1.0-beta2)
 - lithium (0.5.0-rc1)

### Crash Report File
``` 
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: tried to access field net.minecraft.class_3898$class_3208.field_18247 from class net.minecraft.class_3898
	at net.minecraft.class_3898.method_18713(class_3898.java:2749) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3215.method_14096(class_3215.java:467) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:867) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:172) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:134) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:723) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

### Additional Information
Minecraft Version: 1.16.1
Operating System: Mac OS X (x86_64) version 10.15.5
Java Version: 1.8.0_241, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

**Comment by amnotbananaama** [comment] 2020-07-04 01:54
Duplicate of https://github.com/jellysquid3/lithium-fabric/issues/70. This is caused by OptiFine or OptiFabric. From Jellysquid on the [Discord](https://discordapp.com/channels/602796788608401408/602805020861267968/728712724179320953) :
>  Optifabric is not supported.

**Closed as completed** 2020-07-04 03:22 UTC
