### ISSUE TITLE
[1.16.5] Seemingly Random Client Crash

### ISSUE THREAD

**Issue by hugeblank** [jellysquid3/Lithium#234] opened 2021-05-18 08:13 UTC
### Reproduction Steps
I wish I had some way to reproduce this but it's entirely random, ranging from 3 seconds after server log in, to an hour into playing.

Lithium appears to be in the stacktrace, but not before fastutil. Perhaps it could be an upstream thing?

### Crash Report File
[crash-2021-05-14_16.44.05-client.txt](https://github.com/CaffeineMC/lithium-fabric/files/6499505/crash-2021-05-14_16.44.05-client.txt)

**Comment by 2No2Name** [comment] 2021-05-18 14:01
Do you have any idea which mod is adding the method optimizedTileEntityRemoval? This might be a mod compatibility problem with lithium's `mixin.world.block_entity_ticking.collections`. You can add `mixin.world.block_entity_ticking.collections=false` to the lithium config file to work around this.

**Comment by 2No2Name** [comment] 2021-05-18 14:06
I think this is triggered by an interaction with tweakaroos Configs.Fixes.TILE_UNLOAD_OPTIMIZATION. However this should not cause a crash in our code, so this is most likely caused by a bug in the BlockEntityList

**Comment by hugeblank** [comment] 2021-05-19 03:24
> Do you have any idea which mod is adding the method optimizedTileEntityRemoval?

I don't know unfortunately. I wish there was a way to track which mod added which mixin for things like this.

>  I think this is triggered by an interaction with tweakaroos Configs.Fixes.TILE_UNLOAD_OPTIMIZATION

Was this you answering your own question? Just want to make sure I won't be having to do any digging into which mod adds the `optimizedTileEntityRemoval`. 

> You can add `mixin.world.block_entity_ticking.collections=false` to the lithium config file to work around this.

I'll do this, but there'll be no way to confirm if that fixes it given the random and sparse nature of the crash

**Comment by K0-RR** [comment] 2021-05-19 08:06
> I wish there was a way to track which mod added which mixin

I think https://www.curseforge.com/minecraft/mc-mods/mixintrace might be useful if I understand correctly what it does.

**Comment by hugeblank** [comment] 2021-05-19 08:11
> I think https://www.curseforge.com/minecraft/mc-mods/mixintrace might be useful if I understand correctly what it does.

:o oooh, I'll give this a shot! Thanks!

**Comment by hugeblank** [comment] 2021-05-19 12:34
I got another crash, with the suggested mod above, and not enough crashes.

This time it's with *adding* a block entity, but the top part of the traceback is the same. Additionally instead of tweakeroo triggering the crash it was AE2. One thing I did not do was change `mixin.world.block_entity_ticking.collections` to false, I'll do that next. Figured this would be an interesting datapoint since it seems more detailed.

[crash.txt](https://gist.githubusercontent.com/natanfudge/a98abad18093054b453856fa4a5a61fe/raw/9e49ba30a409c7328960a784158da744e0eaf0ae/crash.txt)

**Comment by 2No2Name** [comment] 2021-05-26 20:53
Does it also happen with `mixin.world.block_entity_ticking.collections=false`?

**Comment by hugeblank** [comment] 2021-05-26 23:43
I haven't crashed from this issue since I've set it to false, and that was a few days ago, so probably not? 

I don't know if this issue should be closed though, I'm going to keep playing with it set to false.

**Comment by 2No2Name** [comment] 2021-05-28 22:13
As long as no other users have the same issue, I will assume that it is caused by some combination of mods that you have installed. As you have a workaround, there is no need for further investigation now. It is possible to only use half of the installed mods at a time to find a minimal set of mods that triggers this crash

**Comment by magneticflux-** [comment] 2021-05-30 22:21
> > I wish there was a way to track which mod added which mixin
> 
> I think https://www.curseforge.com/minecraft/mc-mods/mixintrace might be useful if I understand correctly what it does.

If you enable mixin debug output you can Ctrl-F the log for `optimizedTileEntityRemoval` and find what mixin plugin loaded it.

**Comment by 2No2Name** [comment] 2021-06-02 15:25
I think the only way this could happen is offthread modification of the non-threadsafe tile entity lists

**Comment by defineundefine** [comment] 2021-07-22 05:38
I'm having the same issues as well with random crashes. I would try the seemingly working solution above, but I don't what I must change in my .minecraft folder and I don't know what I must change to `mixin.world.block_entity_ticking.collections=false`. Could someone help me with this? The only mods I have are Sodium, Lithium, & Phosphor with the Fabric API.

**Comment by 2No2Name** [comment] 2021-07-30 03:28
Closing as there is a successful workaround that works for the user with that specific combination of mods

**Closed as completed by 2No2Name** 2021-07-30 03:28 UTC
Labels: T-bug, A-mods, S-confirmed
