### ISSUE TITLE
Conflict With Optifabric

### ISSUE THREAD

**Issue by MzKaiser** [jellysquid3/Lithium#251] opened 2021-06-30 12:22 UTC
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **crash report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version

> lithium-fabric-mc1.17-0.7.2
 
### Reproduction Steps

I Just Opened The Game

### Crash Report File

Found conflicting mods: lithium conflicts with {optifabric @ [*]}
|
--Creating Empty clause ?

**Comment by pajicadvance** [comment] 2021-06-30 12:30
Duplicate of #73 , this is intended, Lithium is not compatible with Optifine

**Closed as completed** 2021-07-09 15:56 UTC
