### ISSUE TITLE
Not compatible with Fabric API 0.64.0!

### ISSUE THREAD

**Issue by QianMuu** [jellysquid3/Lithium#404] opened 2022-10-25 08:46 UTC
This is a good optimization module.

However, it is not compatible with the latest version of the fabric api,

Failure to generate a world directly leads to a crash.

Please repair it as soon as possible.

**Comment by 2No2Name** [comment] 2022-10-25 11:46
Can you post the crash report?

**Comment by 2No2Name** [comment] 2022-10-25 13:44
Possible duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/401

**Closed as completed** 2022-10-25 13:44 UTC
Labels: T-bug, E-duplicate, A-mods, S-cannot-repro
