### ISSUE TITLE
Offset must be one of {0f, 0.5f, 1f}. Crash with Supplementaies.

### ISSUE THREAD

**Issue by MehVahdJukaar** [jellysquid3/Lithium#577] opened 2024-11-02 18:30 UTC
### Version Information

Version is new one just gotten from CF on 1.20. Also happens on the forge ports.

### Reproduction Steps

Install Supplementaries new update and click on a Sliding Block.

Sliding block has a block entity that extends MovingPistonBlockEntity

Lithum will make the game crash due to that offset check it added.

Here's the relevant log bit

![image](https://github.com/user-attachments/assets/89b3048e-175b-433c-bcb1-ec9910659a8b)

[latest.log](https://github.com/user-attachments/files/17607959/latest.log)

**Comment by MrRedstoneToGo** [comment] 2024-11-05 20:44
Why did you devs even add this check? To save performance?? Wouldn't it just work fine if you check:

**Comment by MrRedstoneToGo** [comment] 2024-11-05 21:01
What about this?

if (offset < 0f || offset > 1f) {
      throw new IllegalArgumentException("offset must be between 0f and 1f}");
}
        
 I mean, offset is casted to an int either way and there are no index problems.
 But if you, @CaffeineMC , want to round correctly, you can just write that:
 
44       return (int) (2 * offset + 0.5f) + 2 * direction.getId();

**Comment by MehVahdJukaar** [comment] 2024-11-06 00:26
I feel that too isnt enough. Vanilla wouldnt crash with an invalid offset (less than 0 or greater than 1), so, even if in this case it wouldnt matter it should still not implode when an arbitrry number is there, matching the vanilla behavior as it should since its modifying a vanilla class which mods can use and extend.
Adding forced crashes based off random arbitrary assumptions is bad

**Comment by IMS212** [comment] 2024-11-06 00:31
If you look at the code, the optimization requires that. It indexes a LUT of 13 entries based on that information.

**Comment by douira** [comment] 2024-11-08 02:00
This targeted check exists for good reason, specifically because there would be an NPE if the invariant assumed by lithium's optimization is violated, which is an objectively worse error experience. A more productive response to this instead of blocklisting lithium entirely is to use lithium's API to disable this specific lithium optimization with which your code conflicts. It's very easy and we even have [a wiki page that describes how to do it](https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json) and [a list of all the possible optimizations](https://github.com/CaffeineMC/lithium-fabric/blob/develop/lithium-mixin-config.md). You just need to add a custom property to your metadata file (fabric mod json or mod toml on forge). The identifier for this lithium mixin is simply its package suffix `block.moving_block_shapes`. It's just as much effort as adding lithium to your custom (??) mod blocklist, doesn't unnecessarily degrade performance, and avoids breaking users' setups.

**Comment by jellysquid3** [comment] 2024-11-08 03:02
The assertion is not at fault here. Lithium expects for a certain block shape and offset to be used by Pistons and it enables a fast path which relies on that. Fixing the problem is just a matter of having Lithium skip the optimizations specific to that block shape when mods are replacing it.

**Comment by 2No2Name** [comment] 2024-11-08 04:11
@MehVahdJukaar The solution applied now will just throw you back to the vanilla/non-optimized code, if the block offset is not exactly -1, -.5, 0, .5 or 1, as the optimization is specifically made to handle these vanilla cases.

**Comment by MehVahdJukaar** [comment] 2024-11-08 08:02
I didn't know there was a way to disable certain features from a mod mod JSON. That's nice to know . Obviously wouldn't be an ideal solution so I'm glad a proper solution was taken with it falling back to vanilla logic. Will this be applied to 1.20 and 1.21?

**Comment by 2No2Name** [comment] 2024-11-08 11:53
Probably there won't be a backport of this change. I suggest to use the mod json way to disable the optimization in case you still support the older versions

**Comment by MehVahdJukaar** [comment] 2024-11-08 16:36
alright will do. For both 1.21 and 1.20 or just 1.20?


on btw i reply to @douira I dont have a block list, merely a warn list as old 1.20 forge does not allow to specify mod conflicts in mods.toml. Merely use it to show a warning message warning users about a possible so I dont get the reports of that.

**Comment by 2No2Name** [comment] 2024-11-08 16:46
Not sure yet about 1.21

**Comment by MehVahdJukaar** [comment] 2024-11-11 10:32
I added this stuff to fabric.mod.json and i just got a new report about this issue still being there
![image](https://github.com/user-attachments/assets/019cb853-7b7d-4f1f-b16c-6ffbbc53318d)

**Comment by MehVahdJukaar** [comment] 2024-11-11 10:37
> Not sure yet about 1.21

So 1.21 wont receive any more updates? shouldnt this get high priority given it causes a crash? that's what i do at least for my mods, even if its an abandoned version i still release a hotfix.

**Comment by 2No2Name** [comment] 2024-11-11 16:14
> I added this stuff to fabric.mod.json and i just got a new report about this issue still being there 

Yeah there seems to be an issue with the Lithium Configuration after the update to multiloader. That will be fixed in the next release. Thanks for reporting this

**Comment by 2No2Name** [comment] 2024-11-11 16:26
https://github.com/CaffeineMC/lithium-fabric/commit/8ed54ef137d11e73ad5b47627b433488aecafd44

**Closed as completed** 2024-11-17 20:52 UTC
Labels: T-bug, A-mods, R-pending-release, F-good-issue, F-has-workaround

**Comment by MehVahdJukaar** [comment] 2026-02-16 08:30
Why was this closed? I've just gotten an issue of this issue again

**Comment by 2No2Name** [comment] 2026-02-16 09:14
It was closed because it was fixed

**Comment by MehVahdJukaar** [comment] 2026-02-16 12:13
I got given this. Unless the user was not using an updated version it doesn't seem to be fixed at all

[crash-2026-02-15_23.12.12-client-1.txt](https://github.com/user-attachments/files/25339730/crash-2026-02-15_23.12.12-client-1.txt)

**Comment by MehVahdJukaar** [comment] 2026-02-16 13:29
Ok so they weren't using lithium, I got lied to. Btw I don't have the perms to write in the Devs discord channel
