### ISSUE TITLE
Broken skeleton farm with Lithium

### ISSUE THREAD

**Issue by leon0399** [jellysquid3/Lithium#35] opened 2020-04-18 19:04 UTC
Game version: `1.15.2`
Lithium version: `lithium-mc1.15.2-fabric-0.4.6-mod`
Fabric version: `0.5.2.39`

<details>
  <summary>Screenshot</summary>

  ![Mobs cram in a tunnel](https://i.imgur.com/AD6qtVk.png)
</details>

Seems like the right last mob tries to pathfind towards to spawner and declines to enter bubble column

After uninstalling mods, everything works like a charm

**Comment by eatmyvenom** [comment] 2020-04-18 19:14
Please send a latest.log

**Comment by leon0399** [comment] 2020-04-18 19:28
<details>
  <summary>Logs</summary>

  ```
[18:41:08] [main/INFO]: Loading for game Minecraft 1.15.2
[18:41:09] [main/INFO]: [FabricLoader] Loading 37 mods: minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-keybindings-v0@0.1.1+dfdb52d60c, fabricloader@0.7.8+build.189, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-containers-v0@0.1.3+b7f9825d0c, lithium@0.4.6, fabric-dimensions-v1@0.3.0+2ad156310c, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-events-interaction-v0@0.3.0+fac69e320c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, mm@2.0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-resource-loader-v0@0.1.10+06c939b30c, fabric-textures-v0@1.0.4+821cdba70c, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, com_moandjiezana_toml_toml4j@0.7.2, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric@0.5.1+build.294-1.15, carpet@1.3.15, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-networking-v0@0.1.7+12515ed90c, fabric-object-builders-v0@0.1.3+e4c9a9c30c
[18:41:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/opt/minecraft/instances/season4/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[18:41:10] [main/INFO]: Lithium's configuration file was loaded successfully
[18:41:10] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.ai.fast_goal_selection.MixinGoalSelector' as no configuration enables it
[18:41:10] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.ai.fast_goal_selection.MixinGoal' as no configuration enables it
[18:41:10] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.chunk.no_chunk_locking.MixinPalettedContainer' as no configuration enables it
[18:41:10] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.redstone.MixinRedstoneWireBlock' as no configuration enables it
[18:41:10] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.redstone.MixinWorld' as no configuration enables it
[18:41:12] [main/INFO]: Transforming class net/minecraft/class_2382 using patch set 'Modify mutability flags in Vec3i'
[18:41:14] [main/INFO]: Transforming class net/minecraft/class_2338$class_2339 using patch set 'Use mutable fields in Vec3i'
[18:41:24] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[18:41:24] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[18:41:24] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[18:41:24] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[18:41:24] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[18:41:25] [main/INFO]: Definitely not up to no good
[18:41:25] [Server thread/INFO]: Starting minecraft server version 1.15.2
[18:41:25] [Server thread/INFO]: Loading properties
[18:41:25] [Server thread/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[18:41:25] [Server thread/INFO]: Default game type: SURVIVAL
[18:41:25] [Server thread/INFO]: Generating keypair
[18:41:26] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:41:26] [Server thread/INFO]: Using epoll channel type
[18:41:27] [Server thread/INFO]: Preparing level "world"
[18:41:27] [Server thread/INFO]: [CM]: loaded setting combineXPOrbs as false from carpet.conf
[18:41:27] [Server thread/INFO]: [CM]: loaded setting leadFix as true from carpet.conf
[18:41:27] [Server thread/INFO]: [CM]: loaded setting portalSuffocationFix as true from carpet.conf
[18:41:27] [Server thread/INFO]: [CM]: loaded setting antiCheatDisabled as true from carpet.conf
[18:41:27] [Server thread/INFO]: [CM]: loaded setting defaultLoggers as mobcaps,tps from carpet.conf
[18:41:27] [Server thread/INFO]: [CM]: loaded setting unloadedEntityFix as true from carpet.conf
[18:41:27] [Server thread/INFO]: [CM]: loaded setting ctrlQCraftingFix as true from carpet.conf
[18:41:27] [Server thread/INFO]: [CM]: loaded setting placementRotationFix as true from carpet.conf
[18:41:27] [Server thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[18:41:27] [Server thread/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack './world/datapacks/VanillaTweaks_d497667_UNZIP_ME.zip'
[18:41:27] [Server thread/INFO]: Reloading ResourceManager: Default, Fabric Mining Levels (v0), pregen.zip, afk display v1.0.1.zip, anti enderman grief v1.0.0.zip, armour statues v2.6.0.zip, coordinates hud v1.1.1.zip, custom villager shops v1.1.0.zip, double shulker shells v1.2.0.zip, more mob heads v2.3.0.zip, multiplayer sleep v1.0.1.zip, nether portal coords v1.0.0.zip, pillager tools v1.0.1.zip, player head drops v1.0.0.zip, silence mobs v1.0.0.zip, terracotta rotation wrench v1.0.1.zip, track raw statistics v1.2.0.zip, track statistics v1.0.1.zip, villager workstation highlights v1.0.0.zip, wandering trades v1.0.0.zip, VanillaTweaks_c451695.zip, villager death messages v1.0.0.zip, mch030_sushiplate.zip, mch042_courtlady(green).zip, mch043_courtlady(red).zip, mch015_fishbasket.zip, mch017_cookiejar.zip, mch020_valentinesdayflowerpot.zip, mch019_platewithsweets.zip, mch040_weaponstand.zip, mch031_spearsandswords.zip, mch001_steveandalex.zip, mch016_handcartwithfruits.zip, mch041_bureauchair.zip, mch024_scale.zip
[18:42:30] [Server thread/INFO]: Loaded 6 recipes
[18:42:31] [Server thread/WARN]: Found validation problem in {minecraft:entities/ender_dragon}.pools[0].entries[0]: Unknown loot table called minecraft:entities/reference/extra/ender_dragon
[18:42:31] [Server thread/WARN]: Found validation problem in {minecraft:entities/villager}.pools[0].entries[0]: Unknown loot table called minecraft:entities/reference/villager/villager_head
[18:42:32] [Server thread/INFO]: Loaded 648 custom command functions
[18:42:32] [Server thread/ERROR]: Parsing error loading custom advancement main:main/namespace: Expected item to be an item, was unknown string 'minecraft:item'
[18:42:32] [Server thread/INFO]: Loaded 949 advancements
[18:42:33] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:42:36] [Server thread/INFO]: Preparing spawn area: 0%
[18:42:36] [Server thread/INFO]: Preparing spawn area: 0%
[18:42:36] [Server thread/INFO]: Preparing spawn area: 0%
[18:42:36] [Server thread/INFO]: Preparing spawn area: 0%
[18:42:36] [Server thread/INFO]: Preparing spawn area: 0%
[18:42:36] [Server thread/INFO]: Preparing spawn area: 0%
[18:42:36] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[18:42:37] [Server thread/INFO]: Time elapsed: 3623 ms
[18:42:37] [Server thread/INFO]: Done (70.003s)! For help, type "help"
[18:42:41] [Server thread/INFO]: leon0399[/10.10.40.253:45208] logged in with entity id 14 at (579.3000000119209, 13.0625, 97.51249998807907)
[18:42:41] [Server thread/INFO]: leon0399 joined the game
[18:42:42] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2023ms or 40 ticks behind
[18:43:03] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6093ms or 121 ticks behind
[18:49:55] [Server thread/INFO]: [leon0399: Stopping the server]
[18:49:55] [Server thread/INFO]: Stopping server
[18:49:55] [Server thread/INFO]: Saving players
[18:49:55] [Server thread/INFO]: leon0399 lost connection: Disconnected
[18:49:55] [Server thread/INFO]: leon0399 left the game
[18:49:55] [Server thread/INFO]: Saving worlds
[18:49:55] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:the_nether
[18:49:55] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:49:55] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[18:49:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[18:49:56] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:the_end
[18:49:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:49:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:49:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[18:49:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
  ```
</details>

**Comment by eatmyvenom** [comment] 2020-04-18 20:52
From what I can tell its entirely possible that its lithium but it would be difficult to know unless we can get more information, also it is possible that its carpetmod. Try disabling carpet and leaving lithium and test it. Then switch the two and test.

**Comment by eatmyvenom** [comment] 2020-04-18 20:59
There has also been a volunteer to test it, could you provide a wdl and coordinates of the trouble spot?

**Comment by leon0399** [comment] 2020-04-19 12:15
[Here](https://drive.google.com/file/d/1GjL0ZxsZMoVRdpKQkP5UVzAbw1YDLQkB/view?usp=sharing) is my entire server folder, including other mods

`/execute in minecraft:overworld run tp @s 579.40 13.06 97.70 180.07 2.40`, issued spawner

Sorry for Google Drive, Github doesn't allow files > 10MB

**Comment by eatmyvenom** [comment] 2020-04-19 17:23
Okay so this issue is **Confirmed** for version 1.15.2 as someone else was able to reproduce your error with your wdl.

However it appears that the same test in 1.16 snapshots did not yield the same results. 

The commits 8d25649 0670b48 2d6104b 656e449 53e6c79 appear to have had a fix for this but are on the 1.16.x branch of lithium where development occurs.  

1.15.2 is the stable branch of lithium and therefore the changes will be brought into that version however there is no deadline on that.

You can do one of three things at this point, if you would like to, operate your world in 1.16 snapshots. Or you can remove lithium in order to use your contraption. And finally you can keep lithium and wait for the merge into this branch.

Personally I believe that you can pick the final option and modify the contraption temporarily to fix this issue however the issue would remain.

**Comment by leon0399** [comment] 2020-04-20 12:22
@eatmyvenom is there any chance for me to compile 1.16.x branch for 1.15.2? If so, can you please provide some simple instructions?

**Comment by eatmyvenom** [comment] 2020-04-20 19:40
No, you cannot directly compile a version backwards. The only way would be if you know java and fabric development, then you can back port it yourself. 

The reason for this is because some of the optimizations have been changed due to changes in the code of 1.16 snapshots and therefore the code will not be compatible without some work.  As an example, 0f80f9b removed villager brain optimizations due to them being put into vanilla but if that were to be brought into 1.15.x it would be just the removal of an optimization without any reason. 

Overall, I believe you can attempt it but it will be difficult and Jelly will be backporting all of this herself once the 1.16.x branch is considered stable.

**Closed as completed** 2020-06-24 18:36 UTC
Labels: T-bug, S-confirmed, R-pending-release
