### ISSUE TITLE
Game occasionally crashing.

### ISSUE THREAD

**Issue by Neubulae** [jellysquid3/Lithium#107] opened 2020-08-19 14:53 UTC
[crash-2020-08-19_16.55.01-server.txt](https://github.com/jellysquid3/lithium-fabric/files/5097264/crash-2020-08-19_16.55.01-server.txt)

Using version:https://github.com/jellysquid3/lithium-fabric/commit/a7ad0029a6fdcba68ee81e63e98ea39543830bb7

**Comment by 2No2Name** [comment] 2020-08-21 13:06
Try the version at https://github.com/jellysquid3/lithium-fabric/commit/f50b4f9539281e6af0c469b73b12f8f830082649 , it includes several changes to the EntityTrackerEngine which might fix your crash.

**Comment by jellysquid3** [comment] 2020-08-26 15:14
Does this issue still occur with Lithium 0.5.2?

**Comment by 2No2Name** [comment] 2020-08-27 20:19
Yes. I gave Neubulae a modified version that should crash earlier and contain more details in the exception message. Currently I believe an incompatibility with another mod is causing the crash, but so far I am waiting for Neubulae experiencing a crash with the modified version

**Comment by 2No2Name** [comment] 2020-08-30 16:43
Probably same problem as https://github.com/jellysquid3/lithium-fabric/issues/119
I currently suspect fabric-carpet's unloadedEntityFix to cause the problem. So please disable that

**Comment by jellysquid3** [comment] 2020-08-31 06:15
Closing as an external issue caused by https://github.com/gnembon/fabric-carpet/issues/443. The author has since pushed a commit which fixes the problem on their end.

**Closed as completed by jellysquid3** 2020-08-31 06:15 UTC
Labels: T-bug, E-external
